### ISSUE TITLE
uaadb SSL error: sun.security.validator.ValidatorException  when trying to use rds as extenal db 

### ISSUE THREAD

**Issue by addisflava** [cloudfoundry/uaa#1093]
**SECURITY NOTICE: If you have found a security problem in the UAA, please do not file a public github issue. Instead, please send an email to security@cloudfoundry.org**

Thanks for taking the time to file an issue. You'll minimize back and forth and help us help you more effectively by answering all of the following questions as specifically and completely as you can.

### What version of UAA are you running?

What output do you see from `curl <YOUR_UAA>/info -H'Accept: application/json'`

73.3.0
https://s3.amazonaws.com/bosh-compiled-release-tarballs/uaa-73.3.0-ubuntu-xenial-315.64-20190703-005224-823863109-20190703005247.tgz

### How are you deploying the UAA?

I am deploying the UAA

WITH bosh director  using uaa.yml and using external-db-uaa.yml ops files

### What did you do?

If possible, provide a recipe for reproducing the error. Exact `curl` or `uaac` commands with verbose output are helpful. If your problem is configuration-related, please include portions of your uaa.yml or bosh deployment manifest that you believe may be relevant (but do not divulge secrets!)

I deployed uaa with bosh director using external-db-uaa.yml . ii expect the uaa to connect to the rds using ssl with the public rds  certificate https://s3.amazonaws.com/rds-downloads/rds-ca-2015-root.pem. 

```
- type: replace
  path: /instance_groups/name=bosh/jobs/name=uaa/properties/uaadb
  value:
    address: ((external_db_host))
    port: ((external_db_port))
    databases:
      - name: uaa
        tag: uaa
    roles:
      - name: ((external_db_user))
        password: ((external_db_password))
        tag: admin
    db_scheme: postgresql
    require_tls: true
    tls_enabled: true
    tls: enabled
    ca_certs: ((rds_certificate))
    skip_ssl_validation: true (i tried with true and false)
~                             
```

### What did you see instead?

Please include UAA logs if available.

from /var/vcap/sys/log/uaa/uaa.log
```
[2019-09-09 21:57:23.624] uaa - 15 [main] .... ERROR --- RecognizeFailureDispatcherServlet: Fatal error: Unable to start UAA application.
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.cloudfoundry.identity.uaa.security.web.SecurityFilterChainPostProcessor#0' defined in ServletContext resource [/WEB-INF/spring-servlet.xml]: Cannot resolve reference to bean 'identityZoneResolvingFilter' while setting bean property 'additionalFilters' with key [TypedStringValue: value [#{T(org.cloudfoundry.identity.uaa.security.web.SecurityFilterChainPostProcessor.FilterPosition).position(5)}], target type [null]]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'identityZoneResolvingFilter' defined in ServletContext resource [/WEB-INF/spring-servlet.xml]: Cannot resolve reference to bean 'identityZoneProvisioning' while setting bean property 'identityZoneProvisioning'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'identityZoneProvisioning' defined in ServletContext resource [/WEB-INF/spring/multitenant-endpoints.xml]: Cannot resolve reference to bean 'jdbcTemplate' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flyway' defined in class path resource [spring/data-source.xml]: Invocation of init method failed; nested exception is org.flywaydb.core.internal.dbsupport.FlywaySqlException:
Unable to obtain Jdbc connection from DataSource
------------------------------------------------
SQL State  : 08006
Error Code : 0
Message    : SSL error: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

        at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:359) ~[spring-beans-4.3.24.RELEASE.jar:4.3.24.RELEASE]
        at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:108) ~[spring-beans-4.3.24.RELEASE.jar:4.3.24.RELEASE]
        at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveManagedMap(BeanDefinitionValueResolver.java:407) ~[spring-beans-4.3.24.RELEASE.jar:4.3.24.RELEASE]
        at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:165) ~[spring-beans-4.3.24.RELEASE.jar:4.3.24.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1533) ~[spring-beans-4.3.24.RELEASE.jar:4.3.24.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1280) ~[spring-beans-4.3.24.RELEASE.jar:4.3.24.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:551) ~[spring-beans-4.3.24.RELEASE.jar:4.3.24.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:481) ~[spring-beans-4.3.24.RELEASE.jar:4.3.24.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312) ~[spring-beans-4.3.24.RELEASE.jar:4.3.24.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.24.RELEASE.jar:4.3.24.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308) ~[spring-beans-4.3.24.RELEASE.jar:4.3.24.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-4.3.24.RELEASE.jar:4.3.24.RELEASE]
        at org.springframework.context.support.PostProcessorRegistrationDelegate.registerBeanPostProcessors(PostProcessorRegistrationDelegate.java:237) ~[spring-context-4.3.24.RELEASE.jar:4.3.24.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.registerBeanPostProcessors(AbstractApplicationContext.java:703) ~[spring-context-4.3.24.RELEASE.jar:4.3.24.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:527) ~[spring-context-4.3.24.RELEASE.jar:4.3.24.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.configureAndRefreshWebApplicationContext(FrameworkServlet.java:668) ~[spring-webmvc-4.3.24.RELEASE.jar:4.3.24.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:634) ~[spring-webmvc-4.3.24.RELEASE.jar:4.3.24.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:682) ~[spring-webmvc-4.3.24.RELEASE.jar:4.3.24.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.initWebApplicationContext(FrameworkServlet.java:553) ~[spring-webmvc-4.3.24.RELEASE.jar:4.3.24.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.initServletBean(FrameworkServlet.java:494) ~[spring-webmvc-4.3.24.RELEASE.jar:4.3.24.RELEASE]
        at org.springframework.web.servlet.HttpServletBean.init(HttpServletBean.java:171) ~[spring-webmvc-4.3.24.RELEASE.jar:4.3.24.RELEASE]
        at javax.servlet.GenericServlet.init(GenericServlet.java:158) ~[servl`


```

**Comment by strehle** [comment]
outdated, with UAA 75.x we run this without issues in AWS / Postgres combination
