### ISSUE TITLE
UAA with session-store set to database for session sharing across instances

### ISSUE THREAD

**Issue by mazacode** [cloudfoundry/uaa#1364]
This is not a bug request, rather a query:
We are using UAA version 74.13.00. We are trying to leverage session-store (database) for session sharing across multiple instances.
  session-store feature has been available since 74.04.
  Here is the property to be set.
  uaa.servlet.session-store = database
  The issue we are facing is, lot of classes from org.opensaml.* are not serializable, and we have been overriding those by copying those in source structure, and making them serializable.
  I need to use open id as well, and am sure there will be more classes I would need to pull from different libraries, and add serialization.
  But, this really doesnt sound right. 
  Has anyone tried using session-store and without having to work out serializable changes on these library classes?

Here is the log:
[uaa-exception.log](https://github.com/cloudfoundry/uaa/files/4977381/uaa-exception.log)

**Comment by shamus** [comment]
Hi, thanks for the bug report. We've had a few reports of sessions size exceeding the allocated column size in the DB, but none about serialization issues. 

Thanks for providing some logs, those will definitely help in triaging the issue!

**Comment by mazacode** [comment]
Thats interesting. We are using saml, and as a part of session attributes, I see lot of classes from opensaml library are getting persisted, and hence the serialization need.

**Comment by mazacode** [comment]
is there any update on this?

**Comment by mazacode** [comment]
Adding more information.
This is the exception that I got when I enabled database session store on vanilla code (i.e. before starting to override classes to implement Serializable interface)
2020-09-04 16:52:03.002,"[2020-09-04 16:52:03.001] [                                ] uaa - [http-nio-8080-exec-10] ERROR org.cloudfoundry.identity.uaa.home.HomeController:error500 Internal error
org.springframework.core.convert.ConversionFailedException: Failed to convert from type [java.lang.Object] to type [byte[]] for value 'org.cloudfoundry.identity.uaa.provider.saml.ExtendedMetadataDelegateCache@32516014'; nested exception is org.springframework.core.serializer.support.SerializationFailedException: Failed to serialize object using DefaultSerializer; nested exception is java.lang.IllegalArgumentException: DefaultSerializer requires a Serializable payload but received an object of type [org.cloudfoundry.identity.uaa.provider.saml.ExtendedMetadataDelegateCache]
	at org.springframework.core.convert.support.ConversionUtils.invokeConverter(ConversionUtils.java:47) ~[spring-core-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:191) ~[spring-core-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.session.jdbc.JdbcIndexedSessionRepository.serialize(JdbcIndexedSessionRepository.java:589) ~[spring-session-jdbc-2.2.0.RELEASE.jar:2.2.0.RELEASE]
	at org.springframework.session.jdbc.JdbcIndexedSessionRepository.lambda$insertSessionAttributes$5(JdbcIndexedSessionRepository.java:486) ~[spring-session-jdbc-2.2.0.RELEASE.jar:2.2.0.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.lambda$update$0(JdbcTemplate.java:865) ~[spring-jdbc-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:617) ~[spring-jdbc-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:862) ~[spring-jdbc-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:917) ~[spring-jdbc-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.session.jdbc.JdbcIndexedSessionRepository.insertSessionAttributes(JdbcIndexedSessionRepository.java:483) ~[spring-session-jdbc-2.2.0.RELEASE.jar:2.2.0.RELEASE]
	at org.springframework.session.jdbc.JdbcIndexedSessionRepository.access$1300(JdbcIndexedSessionRepository.java:130) ~[spring-session-jdbc-2.2.0.RELEASE.jar:2.2.0.RELEASE]
	at org.springframework.session.jdbc.JdbcIndexedSessionRepository$JdbcSession.lambda$save$10(JdbcIndexedSessionRepository.java:817) ~[spring-session-jdbc-2.2.0.RELEASE.jar:2.2.0.RELEASE]
	at org.springframework.transaction.support.TransactionOperations.lambda$executeWithoutResult$0(TransactionOperations.java:68) ~[spring-tx-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140) ~[spring-tx-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.transaction.support.TransactionOperations.executeWithoutResult(TransactionOperations.java:67) ~[spring-tx-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.session.jdbc.JdbcIndexedSessionRepository$JdbcSession.save(JdbcIndexedSessionRepository.java:799) ~[spring-session-jdbc-2.2.0.RELEASE.jar:2.2.0.RELEASE]
	at org.springframework.session.jdbc.JdbcIndexedSessionRepository$JdbcSession.access$200(JdbcIndexedSessionRepository.java:631) ~[spring-session-jdbc-2.2.0.RELEASE.jar:2.2.0.RELEASE]
	at org.springframework.session.jdbc.JdbcIndexedSessionRepository.save(JdbcIndexedSessionRepository.java:409) ~[spring-session-jdbc-2.2.0.RELEASE.jar:2.2.0.RELEASE]
	at org.springframework.session.jdbc.JdbcIndexedSessionRepository.save(JdbcIndexedSessionRepository.java:130) ~[spring-session-jdbc-2.2.0.RELEASE.jar:2.2.0.RELEASE]
	at org.springframework.session.web.http.SessionRepositoryFilter$SessionRepositoryRequestWrapper.commitSession(SessionRepositoryFilter.java:225) ~[spring-session-core-2.2.0.RELEASE.jar:2.2.0.RELEASE]
	at org.springframework.session.web.http.SessionRepositoryFilter$SessionRepositoryRequestWrapper.access$100(SessionRepositoryFilter.java:192) ~[spring-session-core-2.2.0.RELEASE.jar:2.2.0.RELEASE]
	at org.springframework.session.web.http.SessionRepositoryFilter.doFilterInternal(SessionRepositoryFilter.java:144) ~[spring-session-core-2.2.0.RELEASE.jar:2.2.0.RELEASE]
	at org.springframework.session.web.http.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:82) ~[spring-session-core-2.2.0.RELEASE.jar:2.2.0.RELEASE]
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358) ~[spring-web-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271) ~[spring-web-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.51]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.51]
	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126) ~[catalina.jar:8.5.51]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.51]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.51]
	at org.cloudfoundry.identity.uaa.web.XFrameOptionsDisableFilter.doFilter(XFrameOptionsDisableFilter.java:20) ~[cloudfoundry-identity-server-1.0-mds-228177-im-sam-integration-dev.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.51]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.51]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199) ~[catalina.jar:8.5.51]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) ~[catalina.jar:8.5.51]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:543) ~[catalina.jar:8.5.51]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [catalina.jar:8.5.51]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) [catalina.jar:8.5.51]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:688) [catalina.jar:8.5.51]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [catalina.jar:8.5.51]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [catalina.jar:8.5.51]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:609) [tomcat-coyote.jar:8.5.51]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-coyote.jar:8.5.51]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:818) [tomcat-coyote.jar:8.5.51]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1623) [tomcat-coyote.jar:8.5.51]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:8.5.51]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.5.51]
	at java.lang.Thread.run(Unknown Source) [?:?]

**Comment by mazacode** [comment]
It happens during SAML based login flow where browser calls 
GET http://core.piam.local/saml/discovery?returnIDParam=idp&entityID=core.piam.local&idp=myten&isPassive=true

Any clue to circumvent this issue would really help us, as without session sharing we are really having weird issues during scale up / scale down. Even, rolling deployment causes session outages.

**Comment by shamus** [comment]
Thanks for following up. We're just digging into this now.  I was hoping you might provide a bit more information to help this investigation. 

Could you provide a minimal UAA configuration that demonstrates the problem?

The UAA has a lot of configuration options. We're trying to replicate, but not succeeding with the testbed we currently have in place.

**Comment by mazacode** [comment]
Thanks shamus for looking into it.
I am attaching 3 files.
uaa-common.yml -> common uaa configuration
provider_uaa -> application specific uaa configuration
aviato-saml-config.json -> idp configuration

My observation is, when I make an api call that involves client credentials grant, I dont get any error.
But, when I want to log in using authorization code grant, where SAML flow triggers in, I see the issue.

[uaa-common.yml.txt](https://github.com/cloudfoundry/uaa/files/5218100/uaa-common.yml.txt)
[provider_uaa.yml.txt](https://github.com/cloudfoundry/uaa/files/5218101/provider_uaa.yml.txt)
[aviato-saml-config.json.txt](https://github.com/cloudfoundry/uaa/files/5218102/aviato-saml-config.json.txt)

**Comment by shamus** [comment]
Thanks for the extra config. Unfortunately, it still didn't help us reproduce the issue. 

I think we might still missing some context.

**How are you deploying the UAA?**
- using a bosh release I downloaded from bosh.io
- using cf-deployment
- as part of a commercial Cloud Foundry distribution
- other (please explain)

**How are you using the UAA?**

Are you using the UAA solely as an authorization server integrating with external IdPs? Are you also taking advantage of the UAA's SAML IdP functionality? Are you taking advantage of any other features which might be relevant to debugging this issue?

We _suspect_ you are using the UAA as a SAML IdP. We deduced this from the XML document supplied in the metadataLocation field in `aviato-saml-config.json`:
```<md:SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="http://aviato.user-uaa:8080/uaa_app/saml/idp/SSO/alias/aviato.cloudfoundry-saml-login-user-uaa"/>```

Is that suspicion correct? If so, is the same instance of the UAA acting as both the authorization server and the SAML IdP?

---

If you are using the UAA as a SAML IdP, it's quite likely you've found an issue with the database backed sessions. I don't believe that feature was tested against a UAA in that configuration.

**Comment by mazacode** [comment]
Here are the responses:
How is UAA deployed:
   we download the source code. We build it to create war, and deploy it in tomcat.

How are we using UAA:
   we use 2 UAAs.
    uaa1 --SAML-> uaa2 -SAML/OIDC--> IDP

    You are right that, SAML leg is creating problem. Its not going beyond uaa2.
    We certainly need session persistence. What could we do to address this ? Any workaround or any fix that we can try?

**Comment by mazacode** [comment]
Is there any update on any workaround fix that we can add in code or a release with fix?
It would be great if you could help us with fix in code, as upgrading UAA would be quite heavy activity for us to undertake at this moment.

**Comment by shamus** [comment]
Sorry for the delay.  After some investigation, we've identified that running the UAA with `uaa.servlet.session-store` set to `database` is not compatible with the UAA running as a SAML IdP.

SAML IdP functionality isn't a high priority for us as it doesn't support any core CF feature. I'm not sure we'll invest in fixing this beyond updating the documentation to reflect the limitation.

Thanks for highlighting the problem.

**Comment by mazacode** [comment]
Oh ok  :(
We are stuck as long as we use SAML. 
2 questions:
* Is it possible to guide us for the fix, that we can put in the code? pure guidance and no strings attached
* Could you please confirm that, if we move to OIDC, the problem will arise? This is significant effort, which we are trying to avoid though :(
* Any other option that you think of, to address HA.
   We do use session stickiness, but with kubernates ... instances being added on the fly and removed as per its own algorithm.
   We are facing random session invalidations.
