### ISSUE TITLE
Invalid SQL Parameters Generated with spring-security-oauth2-2.4.1.RELEASE

### ISSUE THREAD

**Issue by ledigiacomo** [cloudfoundry/uaa#1379]
I'm running version 4.30 within a larger project and after updating to Spring Boot 2.1.6 we started seeing SQL errors:
`Filter '(displayName eq "read") and identity_zone_id eq "uaa"' generated invalid SQL
org.springframework.dao.InvalidDataAccessApiUsageException: No value supplied for the SQL parameter '__o': No value registered for key '__o'
	at org.springframework.jdbc.core.namedparam.NamedParameterUtils.buildValueArray(NamedParameterUtils.java:355)
	at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.getPreparedStatementCreator(NamedParameterJdbcTemplate.java:418)
	at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.getPreparedStatementCreator(NamedParameterJdbcTemplate.java:392)
	at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.queryForObject(NamedParameterJdbcTemplate.java:236)
	at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.queryForObject(NamedParameterJdbcTemplate.java:245)
	at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.queryForObject(NamedParameterJdbcTemplate.java:261)
	at org.cloudfoundry.identity.uaa.resources.jdbc.JdbcPagingList.<init>(JdbcPagingList.java:76)
	at org.cloudfoundry.identity.uaa.resources.jdbc.JdbcPagingListFactory.createJdbcPagingList(JdbcPagingListFactory.java:39)
	at org.cloudfoundry.identity.uaa.resources.jdbc.AbstractQueryable.query(AbstractQueryable.java:89)
	at org.cloudfoundry.identity.uaa.resources.jdbc.AbstractQueryable.query(AbstractQueryable.java:71)
	at org.cloudfoundry.identity.uaa.scim.bootstrap.ScimUserBootstrap.addToGroup(ScimUserBootstrap.java:302)
	at org.cloudfoundry.identity.uaa.scim.bootstrap.ScimUserBootstrap.addToGroup(ScimUserBootstrap.java:294)
	at org.cloudfoundry.identity.uaa.scim.bootstrap.ScimUserBootstrap.addGroups(ScimUserBootstrap.java:227)
	at org.cloudfoundry.identity.uaa.scim.bootstrap.ScimUserBootstrap.createNewUser(ScimUserBootstrap.java:222)
	at org.cloudfoundry.identity.uaa.scim.bootstrap.ScimUserBootstrap.addUser(ScimUserBootstrap.java:179)
	at org.cloudfoundry.identity.uaa.scim.bootstrap.ScimUserBootstrap.afterPropertiesSet(ScimUserBootstrap.java:129)`

The culprit is the Spring method
>org.springframework.security.oauth2.common.util.RandomValueStringGenerator.generate()

Used in 
>org.cloudfoundry.identity.uaa.resources.jdbc.SimpleSearchQueryConverter.generateParameterPrefix(String). 

At spring-security-oauth2-2.4.0.RELEASE, they added '-' and '_' to the possible characters that could be included in the generated string; '-' in the parameter name that this is generating is invalid SQL and results in a DataAccessException. Adding a check for the '-' in the generateParameterPrefix(String) method should remediate the issue

**Comment by shamus** [comment]
Thanks for the issue and the PR!

I see you're using 4.30 which came out 4/30/2019. The UAA does regularly release with dependency bumps. `spring security oauth` is bumped in version [74.9.0]( https://github.com/cloudfoundry/uaa/releases/tag/v74.9.0). I'm not aware of any issues with SQL generation reported against that version.

Have you tried upgrading the UAA itself?

**Comment by ledigiacomo** [comment]
Unfortunately upgrading on my end is going to take alot of time and effort, however the relevant code here appears to be entirely unchanged. The bump in 74.9.0 contains version 2.4.0.RELEASE of spring security oauth which will be fine. The change occurred in the next release, 2.4.1.RELEASE. From what I can gather, moving to this version was already attempted and failed https://github.com/cloudfoundry/uaa/pull/1276. 

Edit: My apologies, I realize now I had mis-titled the issue. It should read 2.4.1.RELEASE

**Comment by shamus** [comment]
Those pesky version numbers. Too many to keep track of! :)

Anyway, this makes sense. I have some feedback for the PR. Once that's addressed we can get it merged.

Thanks for your help!
