### ISSUE TITLE
system property java.util.logging.config.file is evaluated wrong

### ISSUE THREAD

**Issue by mvach** [cloudfoundry/uaa#144]
Hi,
when I deploy the uaa.war to tomcat, I run into following exception.
The exception is thrown by version 2.0.3 and also on version 2.1.0.

As you can see, the system property ```-Djava.util.logging.config.file=%22C:/temp/tomcat/conf/logging.properties%22``` is simply evaluated wrong

```
08-Apr-2015 15:01:22.853 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive C:\temp\tomcat\webapps\uaa.war
log4j:ERROR Could not read configuration file from URL [file:/C:/temp/tomcat/bin/-Djava.util.logging.config.file=%22C:/temp/tomcat/conf/logging.properties%22].
java.io.FileNotFoundException: C:\temp\tomcat\bin\-Djava.util.logging.config.file="C:\temp\tomcat\conf\logging.properties" (The filename, directory name, or volume label syntax is incorrect)
        at java.io.FileInputStream.open(Native Method)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.io.FileInputStream.<init>(FileInputStream.java:93)
        at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
        at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
        at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:557)
        at org.apache.log4j.PropertyConfigurator.configure(PropertyConfigurator.java:415)
        at org.springframework.util.Log4jConfigurer.initLogging(Log4jConfigurer.java:72)
        at org.cloudfoundry.identity.uaa.config.YamlServletProfileInitializer.applyLog4jConfiguration(YamlServletProfileInitializer.java:155)
        at org.cloudfoundry.identity.uaa.config.YamlServletProfileInitializer.initialize(YamlServletProfileInitializer.java:109)
        at org.cloudfoundry.identity.uaa.config.YamlServletProfileInitializer.initialize(YamlServletProfileInitializer.java:52)
        at org.springframework.web.servlet.FrameworkServlet.applyInitializers(FrameworkServlet.java:720)
        at org.springframework.web.servlet.FrameworkServlet.configureAndRefreshWebApplicationContext(FrameworkServlet.java:657)
        at org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:624)
        at org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:672)
        at org.springframework.web.servlet.FrameworkServlet.initWebApplicationContext(FrameworkServlet.java:543)
        at org.springframework.web.servlet.FrameworkServlet.initServletBean(FrameworkServlet.java:484)
        at org.springframework.web.servlet.HttpServletBean.init(HttpServletBean.java:136)
        at javax.servlet.GenericServlet.init(GenericServlet.java:158)
        at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1231)
        at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1144)
        at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1031)
        at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4909)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5196)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:917)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1701)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
log4j:ERROR Ignoring configuration file [file:/C:/temp/tomcat/bin/-Djava.util.logging.config.file=%22C:/temp/tomcat/conf/logging.properties%22].
08-Apr-2015 15:01:42.505 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive C:\temp\tomcat\webapps\uaa.war has finished in 19,652 ms
08-Apr-2015 15:01:42.505 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-7081"]
08-Apr-2015 15:01:42.515 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 28934 ms
```

**Comment by fhanik** [comment]
I am not seeing that issue. You report doesn't contain enough information to reproduce the issue.
The UAA looks for the following properties


- logging.file
- logging.path
- logging.config

So my guess is that the tomcat property is getting mangled in there somewhere.

    export CATALINA_OPTS=-Djava.util.logging.config.file=/software/tomcat/apache-tomcat-7.0.55/conf/logging.properties
    ./catalina.sh run
    
    INFO: Deployment of web application archive /software/tomcat/apache-tomcat-7.0.55/webapps/uaa.war has finished in 16,292 ms

The command that catalina.sh runs is

    "/software/java/jdk1.7.0_45_x64/bin/java" -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Djava.util.logging.config=%22/software/tomcat/apache-tomcat-7.0.55/conf/logging.properties%22 -Djava.endorsed.dirs="/software/tomcat/apache-tomcat-7.0.55/endorsed" -classpath "/software/tomcat/apache-tomcat-7.0.55/bin/bootstrap.jar:/software/tomcat/apache-tomcat-7.0.55/bin/tomcat-juli.jar" -Dcatalina.base="/software/tomcat/apache-tomcat-7.0.55" -Dcatalina.home="/software/tomcat/apache-tomcat-7.0.55" -Djava.io.tmpdir="/software/tomcat/apache-tomcat-7.0.55/temp" org.apache.catalina.startup.Bootstrap start

**Comment by mvach** [comment]
Here the exact steps to reproduce:

download tomcat:
  http://archive.apache.org/dist/tomcat/tomcat-8/v8.0.21/bin/apache-tomcat-8.0.21-windows-x64.zip
download latest uaa:
  http://repo.spring.io/libs-release-local/org/cloudfoundry/identity/cloudfoundry-identity-uaa/2.1.0/cloudfoundry-identity-uaa-2.1.0.war 

Extract tomcat to c:\temp\tomcat
Copy cloudfoundry-identity-uaa-2.1.0.war into c:\temp\tomcat\webapps

In windows terminal (cmd)
cd /d c:\temp\tomcat\bin
catalina.bat run

Check the log at the very beginning ~100 lines from the top (right after the dumped certificate).

**Comment by fhanik** [comment]
Seems to happen only on Windows, and the property 'logging.config' is already set when the UAA code is being called, so this happens in Spring Framework, or the configuration of the said framework.

On Linux that property is always null.

**Comment by fhanik** [comment]
Found the culprit
In catalina.bat Tomcat does 

````bash
if not "%LOGGING_CONFIG%" == "" goto noJuliConfig
set LOGGING_CONFIG=-Dnop
if not exist "%CATALINA_BASE%\conf\logging.properties" goto noJuliConfig
set LOGGING_CONFIG=-Djava.util.logging.config.file="%CATALINA_BASE%\conf\logging.properties"
:noJuliConfig
set "JAVA_OPTS=%JAVA_OPTS% %LOGGING_CONFIG%"
````

When the UAA calls ApplicationContext.getEnvironment().getProperty("logging.config") the [property source](http://docs.spring.io/autorepo/docs/spring/4.0.8.RELEASE/javadoc-api/org/springframework/core/env/SystemEnvironmentPropertySource.html) resolves this on Windows

On Unix this doesn't happen, cause the catalina.sh does not export the LOGGING_CONFIG variable and it is not present in the environment that the JVM runs in.

**Comment by fhanik** [comment]
Checking to see if this will suffice
https://github.com/cloudfoundry/uaa/commit/2db707d8de512cd5b2aa3d36ded7f2712821dab3

**Comment by pankaj14073** [comment]
@mvach  after doing all that things , what we have to do next ?
