### ISSUE TITLE
Deployment Issue of UAA in Turkish OS - Dependency component interpretation issue

### ISSUE THREAD

**Issue by Subbu3992** [cloudfoundry/uaa#1447]
### What version of UAA are you running?

UAA version - 74.25.0

### How are you deploying the UAA?

I am deploying the UAA

 - using a bosh release I downloaded from bosh.io
 - deployed the package in tomcat server 9.0.35 in local

### What did you do?

Upon deployment the below component throws the issue as described,

The component velocity-engine-core-2.0.jar which is used by UAA, throws exception for unavailable property. This is because of the “i” character being interpreted as "İ" in Turkish language.

Caused by: java.lang.RuntimeException: Error configuring velocity
at org.cloudfoundry.identity.uaa.util.velocity.VelocityFactory.getEngine(VelocityFactory.java:36)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
... 230 more
**Caused by: java.lang.IllegalArgumentException: No enum constant org.apache.velocity.runtime.RuntimeConstants.SpaceGobbling.LİNES**
at java.base/java.lang.Enum.valueOf(Enum.java:240)
at org.apache.velocity.runtime.RuntimeConstants$SpaceGobbling.valueOf(RuntimeConstants.java:298)
at org.apache.velocity.runtime.RuntimeInstance.initializeSelfProperties(RuntimeInstance.java:349)
at org.apache.velocity.runtime.RuntimeInstance.init(RuntimeInstance.java:238)
at org.apache.velocity.app.VelocityEngine.init(VelocityEngine.java:87)
at org.cloudfoundry.identity.uaa.util.velocity.VelocityFactory.getEngine(VelocityFactory.java:33)
... 235 more

### What did you expect to see? What goal are you trying to achieve with the UAA?

The UAA application should be properly deployed and accessible in Turkish machine

### What did you see instead?

Deployment of UAA fails and application is not getting started

**Comment by sebastianGit** [comment]
The issue might have been resolved in more recent versions of the velocity-engine-core see: https://issues.apache.org/jira/plugins/servlet/mobile#issue/VELOCITY-908

**Comment by strehle** [comment]
@Subbu3992  can you please check if a local build with https://github.com/cloudfoundry/uaa/pull/1486 fixes it. if yes I will merge
