### ISSUE TITLE
LDAP login can cause OptimisticLockingFailureException even if the user hasn't changed

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/uaa#176]
I recently converted my deployment over to LDAP and noticed my smoke tests were getting many 500 errors.

Turns out they are failing with an OptimisticLockingFailureException because I run smoke tests with 3 threads.

Anyone see any issue if https://github.com/cloudfoundry/uaa/blob/master/scim/src/main/java/org/cloudfoundry/identity/uaa/scim/bootstrap/ScimUserBootstrap.java#L120 checked to see if anything actually changed before updating the user?

Or perhaps https://github.com/cloudfoundry/uaa/blob/master/common/src/main/java/org/cloudfoundry/identity/uaa/authentication/manager/LdapLoginAuthenticationManager.java#L80 should indicate in the `ExternalGroupAuthorizationEvent` that the scim user needs to be updated and ScimUserBootstrap should simply look at that?

I'd be happy to submit a PR.  Just wanted a little feedback on direction I should take first.

Mike

```
[2015-06-25 22:20:41.232] uaa - 4591 [http-bio-8080-exec-2] .... ERROR --- SecurityFilterChainPostProcessor$HttpsEnforcementFilter: Uncaught Exception:
org.springframework.dao.OptimisticLockingFailureException: Attempt to update a user (b62a05b1-dc70-496b-8c05-0eb0deb1c9e3) with wrong version: expected=105 but found=104
        at org.cloudfoundry.identity.uaa.scim.jdbc.JdbcScimUserProvisioning.update(JdbcScimUserProvisioning.java:247)
        at org.cloudfoundry.identity.uaa.scim.jdbc.JdbcScimUserProvisioning.update(JdbcScimUserProvisioning.java:62)
        at org.cloudfoundry.identity.uaa.scim.jdbc.JdbcScimUserProvisioning$$FastClassBySpringCGLIB$$8d9e12f9.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:717)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
        at org.springframework.aop.framework.adapter.AfterReturningAdviceInterceptor.invoke(AfterReturningAdviceInterceptor.java:52)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:653)
        at org.cloudfoundry.identity.uaa.scim.jdbc.JdbcScimUserProvisioning$$EnhancerBySpringCGLIB$$db3d957d.update(<generated>)
        at org.cloudfoundry.identity.uaa.scim.bootstrap.ScimUserBootstrap.updateUser(ScimUserBootstrap.java:134)
        at org.cloudfoundry.identity.uaa.scim.bootstrap.ScimUserBootstrap.onApplicationEvent(ScimUserBootstrap.java:169)
        at org.cloudfoundry.identity.uaa.scim.bootstrap.ScimUserBootstrap.onApplicationEvent(ScimUserBootstrap.java:48)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:151)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:128)
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:331)
        at org.cloudfoundry.identity.uaa.authentication.manager.ExternalLoginAuthenticationManager.publish(ExternalLoginAuthenticationManager.java:144)
        at org.cloudfoundry.identity.uaa.authentication.manager.LdapLoginAuthenticationManager.userAuthenticated(LdapLoginAuthenticationManager.java:81)
        at org.cloudfoundry.identity.uaa.authentication.manager.ExternalLoginAuthenticationManager.authenticate(ExternalLoginAuthenticationManager.java:117)
        at org.cloudfoundry.identity.uaa.authentication.manager.ChainedAuthenticationManager.authenticate(ChainedAuthenticationManager.java:78)
        at org.cloudfoundry.identity.uaa.authentication.manager.DynamicZoneAwareAuthenticationManager.authenticate(DynamicZoneAwareAuthenticationManager.java:66)
        at org.cloudfoundry.identity.uaa.authentication.BackwardsCompatibleTokenEndpointAuthenticationFilter.doFilter(BackwardsCompatibleTokenEndpointAuthenticationFilter.java:114)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
        at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:213)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
        at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:64)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
        at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:53)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:91)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
        at org.cloudfoundry.identity.uaa.oauth.BackwardsCompatibleScopeParsingFilter.doFilter(BackwardsCompatibleScopeParsingFilter.java:40)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
        at org.cloudfoundry.identity.uaa.security.web.SecurityFilterChainPostProcessor$UaaLoggingFilter.doFilter(SecurityFilterChainPostProcessor.java:253)
        at org.cloudfoundry.identity.uaa.security.web.SecurityFilterChainPostProcessor$HttpsEnforcementFilter.doFilter(SecurityFilterChainPostProcessor.java:196)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
        at org.cloudfoundry.identity.uaa.zone.IdentityZoneResolvingFilter.doFilterInternal(IdentityZoneResolvingFilter.java:58)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
        at org.cloudfoundry.identity.uaa.web.CorsFilter.doFilterInternal(CorsFilter.java:37)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:213)
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:176)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:344)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:261)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
        at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:683)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:620)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by fhanik** [comment]
As always, we do certainly appreciate PRs. In this case, we could either 

1. Check to see if anything has changed - this can easily get out of sync if new fields are added
2. Skip the version check like we do here - https://github.com/cloudfoundry/uaa/blob/develop/scim/src/main/java/org/cloudfoundry/identity/uaa/scim/jdbc/JdbcScimUserProvisioning.java#L333-L339

**Comment by fhanik** [comment]
You could avoid API/interface changes by setting the version on the ScimUser object to -1

**Comment by youngm** [comment]
Oh, good point.  I'll probably just disable version checks for my test user for now.

**Comment by youngm** [comment]
Turns out that when I disable version checks they just get enabled again when the users gets updated.

It appears that update is missing the same logic that deactivate and verify have.

https://github.com/cloudfoundry/uaa/blob/develop/scim/src/main/java/org/cloudfoundry/identity/uaa/scim/jdbc/JdbcScimUserProvisioning.java#L223

**Comment by youngm** [comment]
Turns out that when I disable version checks they just get enabled again when the users gets updated.

It appears that update is missing the same logic that deactivate and verify have.

https://github.com/cloudfoundry/uaa/blob/develop/scim/src/main/java/org/cloudfoundry/identity/uaa/scim/jdbc/JdbcScimUserProvisioning.java#L223

**Comment by youngm** [comment]
I'd like to propose simply adding a `userUpdated` flag to NewUserAuthenticatedEvent that tells  ScimUserBootstrap [0] if it should update the user in the event or not.  LdapLoginAuthenticationManager [1] would obviously set it to false if it hasn't updated anything.

The default would obviously be true for backwards compatibility.  Thoughts?

[0] https://github.com/cloudfoundry/uaa/blob/master/scim/src/main/java/org/cloudfoundry/identity/uaa/scim/bootstrap/ScimUserBootstrap.java#L120
[1] https://github.com/cloudfoundry/uaa/blob/master/common/src/main/java/org/cloudfoundry/identity/uaa/authentication/manager/LdapLoginAuthenticationManager.java#L80

**Comment by youngm** [comment]
Turns out I'm running into another issue.  If I try to be logged into the same user on 2 different machines then it appears that my auth token gets expired.  Must be using the lastModified date of the user perhaps?  So, I think avoiding updating the user is the correct solution.

Any objections to a PR that does what I described above?

**Comment by youngm** [comment]
After looking at it perhaps `ExternalGroupAuthorizationEvent` would the be a more appropriate place to put the updateUser flag since external auth is who is actually triggering and controlling the update.

**Comment by fhanik** [comment]
@youngm The lastModified check for token expiration has been removed. So I would remove that from the list of issues. No objections to a PR.

**Comment by youngm** [comment]
K, I'll give the new version a spin in a couple of weeks and decide on what kind of PR I want to submit then. :)

**Comment by fhanik** [comment]
Fixed via https://github.com/cloudfoundry/uaa/pull/214
