### ISSUE TITLE
Serialization/deserialization issues of Java Objects stored in UAADB

### ISSUE THREAD

**Issue by MartinSmolny** [cloudfoundry/uaa#181]
We had an issue when moving from CF 205 to CF 210. UAA stores serialized Java Objects in the UAADB / table `oauth_code` when returning an authorization code. The underlying spring security implementation was updated with an incompatible version, i.e. it could not deserialized previously stored instance.
When running UAA jobs of different versions - what will always happen during a canary update of the UAA - this has lead to such exceptions:

    java.io.InvalidClassException:org.springframework.security.core.authority.SimpleGrantedAuthority; local class incompatible: stream classdesc serialVersionUID = 400, local class serialVersionUID = 320
    at org.springframework.security.oauth2.common.util.SerializationUtils.deserialize(SerializationUtils.java:40)
    at org.springframework.security.oauth2.provider.code.JdbcAuthorizationCodeServices$1.mapRow(JdbcAuthorizationCodeServices.java:55)
    at org.springframework.security.oauth2.provider.code.JdbcAuthorizationCodeServices$1.mapRow(JdbcAuthorizationCodeServices.java:52)
    at org.springframework.jdbc.core.RowMapperResultSetExtractor.extractData(RowMapperResultSetExtractor.java:93)
    at org.springframework.jdbc.core.RowMapperResultSetExtractor.extractData(RowMapperResultSetExtractor.java:60)
    at org.springframework.jdbc.core.JdbcTemplate$1.doInPreparedStatement(JdbcTemplate.java:708)
    at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:644)
    at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:695)
    at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:727)
    at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:737)
    at org.springframework.jdbc.core.JdbcTemplate.queryForObject(JdbcTemplate.java:811)
    at org.springframework.security.oauth2.provider.code.JdbcAuthorizationCodeServices.remove(JdbcAuthorizationCodeServices.java:51)
    ...

We have seen this exception in both directions, i.e. an "old" UAA creating the authorization code and a "new" UAA cannot deserialize it, but also a "new" UAA creating the authorization code and the "old" UAA cannot deserialize it.

In a similar situation, when issuing one-time passcodes, the table `expiring_code_store`, is handling similar data much better. Here, a JSON representation of the data is stored, instead of serialized Java Objects. Can we switch the implementation for `oauth_code` to such a concept also, i.e. JSON text instead of serialized Java Objects? Alternatively, can we get spring security framework to stay compatible, i.e. not updating the serialVersionUid and only making compatible changes?

P.S. In mid 2014, around CF 169, we had the same issue when going to serialVersionUid = 320.

**Comment by fhanik** [comment]
Are you able to provide the full stack trace, we would like to see the code path within the UAA aht leads to this

**Comment by MartinSmolny** [comment]
A collegue retrieved that stack trace / log for me, this is all I have - I hope that helps more:

    error={"error":"server_error","error_description":"java.io.InvalidClassException: org.springframework.security.core.authority.SimpleGrantedAuthority; local class incompatible: stream classdesc serialVersionUID = 320, local class serialVersionUID = 400","statusCode":500,"operation":"POST https://uaa.ng.bluemix.net/oauth/token" (https://uaa.ng.bluemix.net/oauth/token%27) }
    
    java.lang.IllegalArgumentException: java.io.InvalidClassException: org.springframework.security.core.authority.SimpleGrantedAuthority; local class incompatible: stream classdesc serialVersionUID = 400, local class serialVersionUID = 320
        at org.springframework.security.oauth2.common.util.SerializationUtils.deserialize(SerializationUtils.java:40)
        at org.springframework.security.oauth2.provider.code.JdbcAuthorizationCodeServices$1.mapRow(JdbcAuthorizationCodeServices.java:55)
        at org.springframework.security.oauth2.provider.code.JdbcAuthorizationCodeServices$1.mapRow(JdbcAuthorizationCodeServices.java:52)
        at org.springframework.jdbc.core.RowMapperResultSetExtractor.extractData(RowMapperResultSetExtractor.java:93)
        at org.springframework.jdbc.core.RowMapperResultSetExtractor.extractData(RowMapperResultSetExtractor.java:60)
        at org.springframework.jdbc.core.JdbcTemplate$1.doInPreparedStatement(JdbcTemplate.java:708)
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:644)
        at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:695)
        at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:727)
        at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:737)
        at org.springframework.jdbc.core.JdbcTemplate.queryForObject(JdbcTemplate.java:811)
        at org.springframework.security.oauth2.provider.code.JdbcAuthorizationCodeServices.remove(JdbcAuthorizationCodeServices.java:51)
        at org.springframework.security.oauth2.provider.code.RandomValueAuthorizationCodeServices.consumeAuthorizationCode(RandomValueAuthorizationCodeServices.java:29)
        at org.springframework.security.oauth2.provider.code.AuthorizationCodeTokenGranter.getOAuth2Authentication(AuthorizationCodeTokenGranter.java:66)
        at org.springframework.security.oauth2.provider.token.AbstractTokenGranter.getAccessToken(AbstractTokenGranter.java:70)
        at org.springframework.security.oauth2.provider.token.AbstractTokenGranter.grant(AbstractTokenGranter.java:65)
        at org.springframework.security.oauth2.provider.CompositeTokenGranter.grant(CompositeTokenGranter.java:38)
        at org.springframework.security.oauth2.provider.endpoint.TokenEndpoint.getAccessToken(TokenEndpoint.java:115)
        at sun.reflect.GeneratedMethodAccessor87.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.springframework.web.method.support.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:215)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:132)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:749)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:689)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:83)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:938)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:870)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:961)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:863)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:646)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:837)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:118)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:84)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
        at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:154)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)

**Comment by fhanik** [comment]
I'll be working on this issue in this story https://www.pivotaltracker.com/story/show/98149612 and closing the original story

**Comment by fhanik** [comment]
Fixed via https://www.pivotaltracker.com/story/show/98149612
