### ISSUE TITLE
LimiterExpirationProcess error repeated infinitely when a UAA server goes idle

### ISSUE THREAD

**Issue by swalchemist** [cloudfoundry/uaa#2081]
### What version of UAA are you running?

develop branch, commit f96b007af

### How are you deploying the UAA?

- locally only using gradlew using the default config files

### What did you do?

When I have the uaa server running on my Macbook and leave the computer idle for an hour or more, several times I've returned to find this error spewing in the uaa log several times per second: `ERROR --- ExpirationBuckets: Second requested outside of current BucketRing window`. Once it starts, it seems to continue indefinitely as long as the server runs. It doesn't seem to have a noticeable effect on performance or functionality, but it does clog the log a great deal.

I've seen this happen three times so far. It seems to happen every time the laptop goes to sleep for more than a few minutes. The last time, however, I'm not sure if the laptop went to sleep at all. Here's a log snippet from the onset of the error, apparently not triggered by a hit to the back end:

```
[2022-10-28T19:36:18.339237Z] uaa - 94573 [http-nio-8080-exec-6] ....  INFO --- RateLimitingFilter: path '/uaa/login.do' (84000ns) -- NOT limited
[2022-10-28T19:36:18.349408Z] uaa - 94573 [http-nio-8080-exec-6] ....  INFO --- SamlKeyManagerFactory: Loaded service provider certificate legacy-saml-key
[2022-10-28T19:36:18.351051Z] uaa - 94573 [http-nio-8080-exec-6] ....  INFO --- NonSnarlMetadataManager: Initialized local service provider for entityID: cloudfoundry-saml-login
[2022-10-28T19:36:18.445025Z] uaa - 94573 [http-nio-8080-exec-6] ....  INFO --- Audit: IdentityProviderAuthenticationSuccess ('marissa'): principal=67a4ec51-7bcc-438c-9d5d-90512a841e9b, origin=[remoteAddress=0:0:0:0:0:0:0:1, sessionId=<SESSION>], identityZoneId=[uaa], authenticationType=[uaa]
[2022-10-28T19:36:18.446906Z] uaa - 94573 [http-nio-8080-exec-6] ....  INFO --- Audit: UserAuthenticationSuccess ('marissa'): principal=67a4ec51-7bcc-438c-9d5d-90512a841e9b, origin=[remoteAddress=0:0:0:0:0:0:0:1, sessionId=<SESSION>], identityZoneId=[uaa]
[2022-10-28T19:36:18.473969Z] uaa - 94573 [http-nio-8080-exec-7] ....  INFO --- RateLimitingFilter: path '/uaa/' (147000ns) -- NOT limited
[2022-10-28T19:36:18.478102Z] uaa - 94573 [http-nio-8080-exec-7] ....  INFO --- SamlKeyManagerFactory: Loaded service provider certificate legacy-saml-key
[2022-10-28T19:36:18.479321Z] uaa - 94573 [http-nio-8080-exec-7] ....  INFO --- NonSnarlMetadataManager: Initialized local service provider for entityID: cloudfoundry-saml-login
[2022-10-28T19:36:18.565283Z] uaa - 94573 [http-nio-8080-exec-7] ....  WARN --- FragmentProcessor: You don't need to put the layout:fragment/data-layout-fragment attribute into the <head> section - the decoration process will automatically copy the <head> section of your content templates into your layout page.
[2022-10-28T21:24:51.643450Z] uaa - 94573 [LimiterExpirationProcess] .... ERROR --- ExpirationBuckets: Second requested outside of current BucketRing window: 1666989741 <= 1666992289 < 1666991789
org.cloudfoundry.identity.uaa.ratelimiting.internal.limitertracking.ExpirationBuckets$BucketRingBoundsException: Second requested outside of current BucketRing window: 1666989741 <= 1666992289 < 1666991789
        at org.cloudfoundry.identity.uaa.ratelimiting.internal.limitertracking.ExpirationBuckets.getBucket(ExpirationBuckets.java:103) ~[cloudfoundry-identity-server-0.0.0.jar:?]
        at org.cloudfoundry.identity.uaa.ratelimiting.internal.limitertracking.ExpirationBuckets.processExpirations(ExpirationBuckets.java:59) ~[cloudfoundry-identity-server-0.0.0.jar:?]
        at org.cloudfoundry.identity.uaa.ratelimiting.internal.limitertracking.ExpirationBuckets.run(ExpirationBuckets.java:69) ~[cloudfoundry-identity-server-0.0.0.jar:?]
        at java.lang.Thread.run(Thread.java:829) ~[?:?]
[2022-10-28T21:24:52.057692Z] uaa - 94573 [LimiterExpirationProcess] .... ERROR --- ExpirationBuckets: Second requested outside of current BucketRing window: 1666989741 <= 1666992290 < 1666991789
org.cloudfoundry.identity.uaa.ratelimiting.internal.limitertracking.ExpirationBuckets$BucketRingBoundsException: Second requested outside of current BucketRing window: 1666989741 <= 1666992290 < 1666991789
        at org.cloudfoundry.identity.uaa.ratelimiting.internal.limitertracking.ExpirationBuckets.getBucket(ExpirationBuckets.java:103) ~[cloudfoundry-identity-server-0.0.0.jar:?]
        at org.cloudfoundry.identity.uaa.ratelimiting.internal.limitertracking.ExpirationBuckets.processExpirations(ExpirationBuckets.java:59) ~[cloudfoundry-identity-server-0.0.0.jar:?]
        at org.cloudfoundry.identity.uaa.ratelimiting.internal.limitertracking.ExpirationBuckets.run(ExpirationBuckets.java:69) ~[cloudfoundry-identity-server-0.0.0.jar:?]
        at java.lang.Thread.run(Thread.java:829) ~[?:?]
[2022-10-28T21:24:52.366053Z] uaa - 94573 [LimiterExpirationProcess] .... ERROR --- ExpirationBuckets: Second requested outside of current BucketRing window: 1666989741 <= 1666992290 < 1666991789
org.cloudfoundry.identity.uaa.ratelimiting.internal.limitertracking.ExpirationBuckets$BucketRingBoundsException: Second requested outside of current BucketRing window: 1666989741 <= 1666992290 < 1666991789
        at org.cloudfoundry.identity.uaa.ratelimiting.internal.limitertracking.ExpirationBuckets.getBucket(ExpirationBuckets.java:103) ~[cloudfoundry-identity-server-0.0.0.jar:?]
        at org.cloudfoundry.identity.uaa.ratelimiting.internal.limitertracking.ExpirationBuckets.processExpirations(ExpirationBuckets.java:59) ~[cloudfoundry-identity-server-0.0.0.jar:?]
        at org.cloudfoundry.identity.uaa.ratelimiting.internal.limitertracking.ExpirationBuckets.run(ExpirationBuckets.java:69) ~[cloudfoundry-identity-server-0.0.0.jar:?]
        at java.lang.Thread.run(Thread.java:829) ~[?:?]
```

And still going hours later:
```
[2022-10-29T01:24:29.513420Z] uaa - 94573 [LimiterExpirationProcess] .... ERROR --- ExpirationBuckets: Second requested outside of current BucketRing window: 1666989741 <= 1667006667 < 1666991789
org.cloudfoundry.identity.uaa.ratelimiting.internal.limitertracking.ExpirationBuckets$BucketRingBoundsException: Second requested outside of current BucketRing window: 1666989741 <= 1667006667 < 1666991789
        at org.cloudfoundry.identity.uaa.ratelimiting.internal.limitertracking.ExpirationBuckets.getBucket(ExpirationBuckets.java:103) ~[cloudfoundry-identity-server-0.0.0.jar:?]
        at org.cloudfoundry.identity.uaa.ratelimiting.internal.limitertracking.ExpirationBuckets.processExpirations(ExpirationBuckets.java:59) ~[cloudfoundry-identity-server-0.0.0.jar:?]
        at org.cloudfoundry.identity.uaa.ratelimiting.internal.limitertracking.ExpirationBuckets.run(ExpirationBuckets.java:69) ~[cloudfoundry-identity-server-0.0.0.jar:?]
        at java.lang.Thread.run(Thread.java:829) ~[?:?]
```

**Comment by swalchemist** [comment]
Reproduced this on the `ratestatusprivate` branch commit `4450d4d6b0ca9f3ae61815349de69f816bacc625` in the same way as before.

```
[2022-11-30T21:29:27.964571Z] uaa - 24415 [LimiterExpirationProcess] .... ERROR --- ExpirationBuckets: Second requested outside of current BucketRing window: 1669841134 <= 1669843765 < 1669843182
org.cloudfoundry.identity.uaa.ratelimiting.internal.limitertracking.ExpirationBuckets$BucketRingBoundsException: Second requested outside of current BucketRing window: 1669841134 <= 1669843765 < 1669843182
        at org.cloudfoundry.identity.uaa.ratelimiting.internal.limitertracking.ExpirationBuckets.getBucket(ExpirationBuckets.java:103) ~[cloudfoundry-identity-server-0.0.0.jar:?]
        at org.cloudfoundry.identity.uaa.ratelimiting.internal.limitertracking.ExpirationBuckets.processExpirations(ExpirationBuckets.java:59) ~[cloudfoundry-identity-server-0.0.0.jar:?]
        at org.cloudfoundry.identity.uaa.ratelimiting.internal.limitertracking.ExpirationBuckets.run(ExpirationBuckets.java:69) ~[cloudfoundry-identity-server-0.0.0.jar:?]
        at java.lang.Thread.run(Thread.java:829) ~[?:?]
```

**Comment by strehle** [comment]
@swalchemist is it still an issue ?

**Comment by strehle** [comment]
please re-open if you still see errors
