### ISSUE TITLE
Avoid necessity to configure SAML SP in UAA

### ISSUE THREAD

**Issue by torsten-sap** [cloudfoundry/uaa#2741]
### What version of UAA are you running?

76.30

### How are you deploying the UAA?

- using cf-deployment

### What did you do?

Usage of UAA without the need of SAML.

### What did you expect to see? What goal are you trying to achieve with the UAA?

No need to configure SAML SP (including private key + certificate etc.) in uaa.yml.

### What did you see instead?

SAML SP configuration (private key + certificate etc.) is required in uaa.yml. Otherwise, UAA will not startup.

**Comment by strehle** [comment]
Reproduce the issue:

1. remove https://github.com/cloudfoundry/uaa/blob/develop/scripts/cargo/uaa.yml#L58-L99
2. start uaa 

Open /login

The IdentityZone should be usable even without SAML keys, but there is execption:

.....a.lang.NullPointerException: Cannot invoke "org.springframework.security.saml.key.KeyManager.getDefaultCredentialName()" because the return value of "org.cloudfoundry.identity.uaa.zone.IdentityZoneHolder.getSamlSPKeyManager()" is null
        at org.cloudfoundry.identity.uaa.provider.saml.ZoneAwareKeyManager.getDefaultCredentialName(ZoneAwareKeyManager.java:41) ~[cloudfoundry-identity-server-0.0.0.jar:?]
        at org.springframework.security.saml.metadata.MetadataGenerator.getSigningKey(MetadataGenerator.java:802) ~[spring-security-saml2-core-1.0.10.RELEASE.jar:1.0.10.RELEASE]
        at org.springframework.security.saml.metadata.MetadataGenerator.buildSPSSODescriptor(MetadataGenerator.java:323) ~[spring-security-saml2-core-1.0.10.RELEASE.jar:1.0.10.RELEASE]
        at org.cloudfoundry.identity.uaa.provider.saml.ZoneAwareMetadataGenerator.buildSPSSODescriptor(ZoneAwareMetadataGenerator.java:101) ~[cloudfoundry-identity-server-0.0.0.jar:?]
        at org.springframework.security.saml.metadata.MetadataGenerator.generateMetadata(MetadataGenerator.java:189) ~[spring-security-saml2-core-1.0.10.RELEASE.jar:1.0.10.RELEASE]

**Comment by hsinn0** [comment]
We will plan to look into it to prioritize in next iteration planning session.

**Comment by aramprice** [comment]
Is there work planned to address this issue?

**Comment by strehle** [comment]
yes, especially from SAP side, because we have many UAAs where SAML should not be active because we dont need it.

We waited until the shift to new opensaml 4, which is now done , so we will work on it

**Comment by fhanik** [comment]
Changing default zone SAML configuration from required to optional is ok. Change should stay backwards compatible for the installations that have all configuration options present.
