### ISSUE TITLE
Excluding Authorities from a access token cause load configuration error 

### ISSUE THREAD

**Issue by ilipkind** [cloudfoundry/uaa#280]
UAA Yaml configuration allows excluding authorities based on following fix: https://github.com/cloudfoundry/uaa/commit/bb4ebfd5f2d98dd92e5734ebb5509a3360aa2928 
However when we run with this configuration we getting follow exception during startup:

 OUT Caused by: org.yaml.snakeyaml.error.YAMLException: Cannot create property=claims for JavaBean=org.cloudfoundry.identity.uaa.UaaConfiguration$Jwt$Token@54750ae0; Unable to find property 'claims' on class: org.cloudfoundry.identity.uaa.UaaConfiguration$Jwt$Token
2015-12-16T15:20:05.03-0800 [App/3]      OUT 	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:299)
2015-12-16T15:20:05.03-0800 [App/3]      OUT 	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:189)
2015-12-16T15:20:05.03-0800 [App/3]      OUT 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182)
2015-12-16T15:20:05.03-0800 [App/3]      OUT 	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:296)
2015-12-16T15:20:05.03-0800 [App/3]      OUT 	... 45 more
2015-12-16T15:20:05.03-0800 [App/3]      OUT Caused by: org.yaml.snakeyaml.error.YAMLException: Unable to find property 'claims' on class: org.cloudfoundry.identity.uaa.UaaConfiguration$Jwt$Token
2015-12-16T15:20:05.03-0800 [App/3]      OUT 	at org.yaml.snakeyaml.introspector.PropertyUtils.getProperty(PropertyUtils.java:132)
2015-12-16T15:20:05.03-0800 [App/3]      OUT 	at org.yaml.snakeyaml.introspector.PropertyUtils.getProperty(PropertyUtils.java:121)
2015-12-16T15:20:05.03-0800 [App/3]      OUT 	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.getProperty(Constructor.java:308)
2015-12-16T15:20:05.03-0800 [App/3]      OUT 	at org.cloudfoundry.identity.uaa.config.CustomPropertyConstructor$CustomPropertyConstructMapping.getProperty(CustomPropertyConstructor.java:71)
2015-12-16T15:20:05.03-0800 [App/3]      OUT 	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:240)

Looking at the class https://github.com/cloudfoundry/uaa/blob/master/common/src/main/java/org/cloudfoundry/identity/uaa/UaaConfiguration.java Token class  surely don't have "claims" member as part of org.cloudfoundry.identity.uaa.UaaConfiguration$Jwt$Token class. Can it be fixed? It would be nice to have test that covers that use case.

**Comment by fhanik** [comment]
Yes, we can make this a part of a bigger story to properly validate all our config.

**Comment by ilipkind** [comment]
Thanks @fhanik, make sense

**Comment by Bitty9** [comment]
When I run uaa 3.2.0 locally with -Djwt.token.claims.exclude="authorities" I see that the property is set. 
``
15:27:34.371 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.IvyLoggingAdaper] setting 'jwt.token.claims.exclude' to 'authorities'
``

However, when I use uaac to get an access token for the admin client I still see authorities in the token. I have not tried setting the property via uaa.yml yet.

``
  jti: 25cd79ab-4597-46a8-b6dd-7fdfd667b9d6
  sub: admin
  authorities: clients.read clients.secret clients.write uaa.admin clients.admin scim.write scim.read
  scope: clients.read clients.secret clients.write uaa.admin clients.admin scim.write scim.read
  client_id: admin
  cid: admin
  azp: admin
  grant_type: client_credentials
  rev_sig: 466711f6
  iat: 1457392609
  exp: 1457435809
  iss: http://localhost:8080/uaa/oauth/token
  zid: uaa
  aud: admin clients uaa scim
``

``
 uaac info
  app
    version: 3.2.0 
``

**Comment by fhanik** [comment]
I'm guessing you are running "gradle" . Gradle doesn't forward system
properties to the running tomcat (cargo) container

Filip

**Comment by Bitty9** [comment]
Thanks for the quick response, @fhanik. 
Even after setting the system property for the local cargo container, I still see the authorities in the token. I am able to exclude the authorities with the uaa.yml which is how I will likely set the property anyway.

``
Starting action 'run' for local container 'Tomcat 7.x'
Container properties = [:]
System properties = [spring.profiles.active:default, jwt.token.claims.exclude:authorities, smtp.host:localhost, smtp.port:2525]
``

**Comment by fhanik** [comment]
@Bitty9 
I believe that property is a Yaml `list`. Meaning, that specifying a string as a system property will not work. You would have to specify it as a list
