### ISSUE TITLE
UAA unable to connect to SAML provider Azure SSO

### ISSUE THREAD

**Issue by garyliu-philips** [cloudfoundry/uaa#3056]
Hi,

We are setting up a SAML based SSO between Azure AD and Cloud Foundry. However it doesn't re-direct to the Azure login page as we expected after we put in our email address as username. We found some error message in the `/var/vcap/sys/log/uaa/catalina.log` file (see bottom attachment). 

### What version of UAA are you running?

What output do you see from `curl <YOUR_UAA>/info -H'Accept: application/json'`?

### How are you deploying the UAA?

I am deploying the UAA
- using cf-deployment v42.6.0

### What did you do?

Below is the uaa-saml.yml configure.

```
- type: replace
  path: /instance_groups/name=uaa/jobs/name=uaa/properties/login/saml/providers?
  value:
    code1:
      override: true
      assertionConsumerIndex: 0
      metadataTrustCheck: false
      storeCustomAttributes: true
      idpMetadata: ((saml_provider_idpMetadata))
      nameID: urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified
      showSamlLoginLink: true
      linkText: ((saml_provider_linkText))
      groupMappingMode: AS_SCOPES
      externalGroupsWhitelist: ["*"]
      skipSslValidation: true
      attributeMappings:
        email: user.mail
        sn: user.surname
        given_name: user.givenname
        uid: user.onpremisessamaccountname
        Unique User Identifier: user.userprincipalname
      emailDomain: [abc.com]
- type: replace
  path: /instance_groups/name=uaa/jobs/name=uaa/properties/login/idpDiscoveryEnabled?
  value: true

- type: replace
  path: /instance_groups/name=uaa/jobs/name=uaa/properties/login/saml/entityID?
  value: ((saml_entity_id))

- type: replace
  path: /instance_groups/name=uaa/jobs/name=uaa/properties/login/saml/entityBaseURL?
  value: ((saml_entity_base_url))

- type: replace
  path: /instance_groups/name=uaa/jobs/name=uaa/properties/login/saml/wantAssertionSigned?
  value: true

- type: replace
  path: /instance_groups/name=uaa/jobs/name=uaa/properties/login/saml/disableInResponseToCheck?
  value: true
```

### What did you expect to see? What goal are you trying to achieve with the UAA?
After putting my Azure AD username 'eample@abc.com' in the UAA login page, it should re-direct to login.microsoftonline.com and prompt for credential.

### What did you see instead?
It did not redirect but stay on the same page

Please include UAA logs if available.

```
21-Sep-2024 14:00:05.322 WARNING [https-jsse-nio-8443-exec-19] com.google.common.cache.LocalCache$Segment.lambda$loadAsync$0 Exception thrown during refresh
        java.util.concurrent.ExecutionException: org.springframework.web.client.ResourceAccessException: I/O error on GET request for "https://login.microsoftonline.com:443/***/federationmetadata/2007-06/federationmetadata.xml": login.microsoftonline.com: Name or service not known; nested exception is java.net.UnknownHostException: login.microsoftonline.com: Name or service not known
                at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:594)
                at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:553)
                at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:110)
                at com.google.common.util.concurrent.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:247)
                at com.google.common.cache.LocalCache$Segment.getAndRecordStats(LocalCache.java:2349)
                at com.google.common.cache.LocalCache$Segment.lambda$loadAsync$0(LocalCache.java:2329)
                at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
                at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1298)
                at com.google.common.util.concurrent.AbstractFuture.addListener(AbstractFuture.java:762)
                at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.addListener(AbstractFuture.java:133)
                at com.google.common.cache.LocalCache$Segment.loadAsync(LocalCache.java:2326)
                at com.google.common.cache.LocalCache$Segment.refresh(LocalCache.java:2397)
                at com.google.common.cache.LocalCache$Segment.scheduleRefresh(LocalCache.java:2374)
                at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2069)
                at com.google.common.cache.LocalCache.get(LocalCache.java:4017)
                at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4040)
                at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4989)
                at org.cloudfoundry.identity.uaa.cache.StaleUrlCache.getUrlContent(StaleUrlCache.java:61)
                at org.cloudfoundry.identity.uaa.cache.StaleUrlCache.getUrlContent(StaleUrlCache.java:54)
                at org.cloudfoundry.identity.uaa.provider.saml.FixedHttpMetaDataProvider.fetchMetadata(FixedHttpMetaDataProvider.java:29)
                at org.cloudfoundry.identity.uaa.provider.saml.SamlIdentityProviderConfigurator.configureURLMetadata(SamlIdentityProviderConfigurator.java:176)
                at org.cloudfoundry.identity.uaa.provider.saml.SamlIdentityProviderConfigurator.getExtendedMetadataDelegate(SamlIdentityProviderConfigurator.java:133)
                at org.cloudfoundry.identity.uaa.provider.saml.NonSnarlMetadataManager.getAvailableProviders(NonSnarlMetadataManager.java:149)
                at org.cloudfoundry.identity.uaa.provider.saml.NonSnarlMetadataManager.getHostedSPName(NonSnarlMetadataManager.java:430)
                at org.springframework.security.saml.metadata.MetadataGeneratorFilter.processMetadataInitialization(MetadataGeneratorFilter.java:100)
                at org.springframework.security.saml.metadata.MetadataGeneratorFilter.doFilter(MetadataGeneratorFilter.java:86)
                at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361)
                at org.cloudfoundry.identity.uaa.authentication.UTF8ConversionFilter.validateParamsAndContinue(UTF8ConversionFilter.java:75)
                at org.cloudfoundry.identity.uaa.authentication.UTF8ConversionFilter.doFilter(UTF8ConversionFilter.java:59)
                at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361)
                at org.cloudfoundry.identity.uaa.security.web.ContentSecurityPolicyFilter.doFilterInternal(ContentSecurityPolicyFilter.java:33)
                at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
                at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361)
                at org.cloudfoundry.identity.uaa.web.HeaderFilter.doFilter(HeaderFilter.java:52)
                at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361)
                at org.cloudfoundry.identity.uaa.metrics.UaaMetricsFilter.doFilterInternal(UaaMetricsFilter.java:86)
                at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
                at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361)
                at brave.servlet.TracingFilter.doFilter(TracingFilter.java:80)
                at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361)
                at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:225)
                at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:190)
                at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354)
                at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:168)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
                at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
                at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:168)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
                at org.springframework.session.web.http.SessionRepositoryFilter.doFilterInternal(SessionRepositoryFilter.java:142)
                at org.springframework.session.web.http.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:82)
                at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354)
                at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:168)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
                at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:129)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:168)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
                at org.cloudfoundry.identity.uaa.ratelimiting.RateLimitingFilter$WithLimitingFilter.doFilter(RateLimitingFilter.java:124)
                at org.cloudfoundry.identity.uaa.ratelimiting.RateLimitingFilter.doFilter(RateLimitingFilter.java:75)
                at javax.servlet.http.HttpFilter.doFilter(HttpFilter.java:53)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:168)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
                at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:168)
                at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
                at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
                at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
                at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
                at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660)
                at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:761)
                at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
                at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:346)
                at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:383)
                at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
                at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:936)
                at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791)
                at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
                at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
                at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
                at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
                at java.base/java.lang.Thread.run(Thread.java:840)
        Caused by: org.springframework.web.client.ResourceAccessException: I/O error on GET request for "https://login.microsoftonline.com:443/1a407a2d-7675-4d17-8692-b3ac285306e4/federationmetadata/2007-06/federationmetadata.xml": login.microsoftonline.com: Name or service not known; nested exception is java.net.UnknownHostException: login.microsoftonline.com: Name or service not known
```

**Comment by garyliu-philips** [comment]
I tested initializing the SAML request from the Azure AD end and the Reply URL works and I was able to login. So it must be the UAA end which cannot redirect user with `@abc.com` to Azure.
