### ISSUE TITLE
redirect to client application is not happening

### ISSUE THREAD

**Issue by sujitkumarsingh** [cloudfoundry/uaa#590]
This was working fine with previous version but after upgrade we are facing below issue. Please let me know if we are missing any configuration.
Description:
After login successfully, the UAA does not redirect to client application. I could see the below log:
java.lang.IllegalArgumentException: An invalid character [34] was present in the Cookie value
	at org.apache.tomcat.util.http.Rfc6265CookieProcessor.validateCookieValue(Rfc6265CookieProcessor.java:162)
	at org.apache.tomcat.util.http.Rfc6265CookieProcessor.generateHeader(Rfc6265CookieProcessor.java:111)
	at org.apache.catalina.connector.Response.generateCookieString(Response.java:989)
	at org.apache.catalina.connector.Response.addCookie(Response.java:937)
	at org.apache.catalina.connector.ResponseFacade.addCookie(ResponseFacade.java:384)
	at javax.servlet.http.HttpServletResponseWrapper.addCookie(HttpServletResponseWrapper.java:58)
	at javax.servlet.http.HttpServletResponseWrapper.addCookie(HttpServletResponseWrapper.java:58)
	at javax.servlet.http.HttpServletResponseWrapper.addCookie(HttpServletResponseWrapper.java:58)
	at org.cloudfoundry.identity.uaa.login.AccountSavingAuthenticationSuccessHandler.setSavedAccountOptionCookie(AccountSavingAuthenticationSuccessHandler.java:71)
	at org.cloudfoundry.identity.uaa.login.AccountSavingAuthenticationSuccessHandler.onAuthenticationSuccess(AccountSavingAuthenticationSuccessHandler.java:46)

However, if I manually go to my client application and refresh it then it fetches the access_token. We are using implicit grant_type.

**Comment by sujitkumarsingh** [comment]
Update:
This problem seems to be with tomcat version > 8.5.x as it ran fine when I am using tomcat version 8.0.x whereas it appears in tomcat 9.0.x. 
However, the prior version of UAA (3.6.x) was running fine on tomcat 9.0.x. Hope this information will help you in reproducing the issue.

**Comment by strehle** [comment]
hi , 

see https://github.com/cloudfoundry/uaa/issues/563 , which is solved for UAA 4.0 already.
https://github.com/cloudfoundry/uaa/issues/566

regards,
_markus

**Comment by sujitkumarsingh** [comment]
@strehle  Thanks for quick response.

**Comment by sujitkumarsingh** [comment]
@strehle . Any idea when this version will be released as I could see 3.14.0 as the latest.

**Comment by strehle** [comment]
@sreetummidi  : can you please answer I assume 4 weeks then UAA 4 should be ready ?
