### ISSUE TITLE
Getting access_confirmation_error

### ISSUE THREAD

**Issue by sujitkumarsingh** [cloudfoundry/uaa#637]
Hi,
After taking latest version of UAA we are getting below exception. Please let me know if this an known issue or if we are missing something uaa.yml:

Log:
cloudfoundry-identity-server - ???? [http-nio-8080-exec-6] .... ERROR --- TemplateEngine: [THYMELEAF][http-nio-8080-exec-6] Exception processing template "access_confirmation_error": Exception evaluating SpringEL expression: "@environment.getProperty('login.branding.footerLinks', Class.forName('java.util.Map'))" (template: "layouts/main" - line 45, col 14)
org.thymeleaf.exceptions.TemplateProcessingException: Exception evaluating SpringEL expression: "@environment.getProperty('login.branding.footerLinks', Class.forName('java.util.Map'))" (template: "layouts/main" - line 45, col 14)
	at org.thymeleaf.spring4.expression.SPELVariableExpressionEvaluator.evaluate(SPELVariableExpressionEvaluator.java:290)
	at org.thymeleaf.standard.expression.VariableExpression.executeVariableExpression(VariableExpression.java:165)
	at org.thymeleaf.standard.expression.SimpleExpression.executeSimple(SimpleExpression.java:66)
	at org.thymeleaf.standard.expression.Expression.execute(Expression.java:109)
	at org.thymeleaf.standard.expression.Expression.execute(Expression.java:138)

**Comment by sujitkumarsingh** [comment]
I found that the problem was with main.html which was customized by us. The main.html used was from the older version of UAA. The issue got resolved after taking the latest main.html file and customized little bit as per our need.
I am closing the issue.
