### ISSUE TITLE
Nullpointer exception in UAA

### ISSUE THREAD

**Issue by binoydev** [cloudfoundry/uaa#640]
UAA - v4.4.0 : Configured saml key and some users in uaa.yml. Started UAA in default profile. When trying to access 
http://127.0.0.1:8080/uaa/oauth/token
grant_type:password
username:paul
password:wombat
client_id:app
client_secret:appclientsecret
got this exception
 java.lang.NullPointerException
	at org.cloudfoundry.identity.uaa.oauth.UaaTokenServices.createRefreshToken(UaaTokenServices.java:897)
	at org.cloudfoundry.identity.uaa.oauth.UaaTokenServices.createAccessToken(UaaTokenServices.java:657)
	at org.springframework.security.oauth2.provider.token.AbstractTokenGranter.getAccessToken(AbstractTokenGranter.java:70)
	at org.springframework.security.oauth2.provider.token.AbstractTokenGranter.grant(AbstractTokenGranter.java:65)
	at org.springframework.security.oauth2.provider.CompositeTokenGranter.grant(CompositeTokenGranter.java:38)
	at org.springframework.security.oauth2.provider.endpoint.TokenEndpoint.postAccessToken(TokenEndpoint.java:132)
	at org.cloudfoundry.identity.uaa.oauth.token.UaaTokenEndpoint.doDelegatePost(UaaTokenEndpoint.java:80)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	

Full stack trace at  https://gist.github.com/binoydev/f618cb13a2ff1b958676a102fa9ec0e0

**Comment by fhanik** [comment]
https://github.com/cloudfoundry/uaa/blob/9b1a790c5a218b1c8ea0dcc15f4a751de28678ef/server/src/main/java/org/cloudfoundry/identity/uaa/oauth/UaaTokenServices.java#L897-L897

That line could indicate that there isn't an JWT signing key configured.

**Comment by binoydev** [comment]
Thankyou @fhanik . I missed to enable jwt attributes in uaa.yml.
But instead of server error , jwt not configured response would be more helpful.

**Comment by fhanik** [comment]
absolutely! We are lagging on the configuration validation

**Comment by fhanik** [comment]
Closing via: https://github.com/cloudfoundry/uaa/commit/64e92de440851a4caa8cbf07f601f387ca6a399e
