### ISSUE TITLE
Login failed due to bad credentials error

### ISSUE THREAD

**Issue by clongbupt** [cloudfoundry/uaa#698]
I am deploying the UAA using cf-release

While using cf to login, would be rejected due to Bad credentials

Some errors showed below:
```
ClientDetailsAuthenticationProvider: Authentication failed: password does not match stored value

error="unauthorized", erro_description="Bad credentials"
```

Listed below there are some other errors when deploying v260 :
```
[2017-09-18 16:08:00.757] uaa - 17849 [localhost-startStop-1] .... ERROR --- YamlConfigurationValidator: Failed to load YAML validation bean. Your YAML file may be invalid.
Cannot create property=scim for JavaBean=org.cloudfoundry.identity.uaa.impl.config.UaaConfiguration@517cb18f
 in 'string', line 1, column 1:
    scim:
    ^
Cannot create property=user for JavaBean=org.cloudfoundry.identity.uaa.impl.config.UaaConfiguration$Scim@313d5774
 in 'string', line 2, column 3:
      groups: {zones.read: Read identi ...
      ^
Unable to find property 'user' on class: org.cloudfoundry.identity.uaa.impl.config.UaaConfiguration$Scim
 in 'string', line 18, column 9:
      user: {override: true}
            ^

 in 'string', line 2, column 3:
      groups: {zones.read: Read identi ...
      ^

        at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:313)
        at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:190)
        at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:346)
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:184)
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:143)
        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:129)
        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:505)
        at org.yaml.snakeyaml.Yaml.load(Yaml.java:424)
        at org.cloudfoundry.identity.uaa.impl.config.YamlConfigurationValidator.afterPropertiesSet(YamlConfigurationVa
lidator.java:86)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAuto
wireCapableBeanFactory.java:1687)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowir
eCapableBeanFactory.java:1624)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireC
apableBeanFactory.java:555)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCap
ableBeanFactory.java:483)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanReg
istry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListab
leBeanFactory.java:742)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractAppl
icationContext.java:866)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542)
```

Versions that we've been tried:

```
cf-release: v261 / v260 / v240 / v230 / v225
uaa-release: v37 / v36 / unknown / unkown / unknown 
uaa: 4.2.0 / 4.1.0 / 3.4.2 / 3.0.1 / unkown
```

I would see from `curl <YOUR_UAA>/info -H'Accept: application/json'`

```
<!DOCTYPE html><html><head><title>Apache Tomcat/8.0.39 - Error report</title><style type="text/css">H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}.line {height: 1px; background-color: #525D76; border: none;}</style> </head><body><h1>HTTP Status 400 - {&quot;error&quot;: &quot;request must be over https&quot;}</h1><div class="line"></div><p><b>type</b> Status report</p><p><b>message</b> <u>{&quot;error&quot;: &quot;request must be over https&quot;}</u></p><p><b>description</b> <u>The request sent by the client was syntactically incorrect.</u></p><hr class="line"><h3>Apache Tomcat/8.0.39</h3></body></html>
```

manifest configuration related to cf login in uaa scim
```
      scim:
        userids_enabled: true
        users:
          - name: admin
            password: ****
            groups:
              - scim.write
              - scim.read
              - openid
              - cloud_controller.admin
              - doppler.firehose
              - routing.router_groups.read
```

**Comment by xiaozhu36** [comment]
I also happened the similar issues and I tried cf-release v220 and v225.

**Comment by fhanik** [comment]
> ClientDetailsAuthenticationProvider: Authentication failed: password does not match stored value
> error="unauthorized", erro_description="Bad credentials"

this is not the username failing. This is the client_id/client_secret combination that is wrong.

Your manifest should have a client with client_id=`cf` and client_secret=`""` for `cf login` to work
