### ISSUE TITLE
Saved-Account cookies causing 400

### ISSUE THREAD

**Issue by 6palace** [cloudfoundry/uaa#794]
### What version of UAA are you running?

{"app":{"version":"4.10.0"},"links":{"uaa":"http://localhost:8080/uaa","passwd":"/forgot_password","login":"http://localhost:8080/uaa","register":"/create_account"},"zone_name":"uaa","entityID":"cloudfoundry-saml-login","commit_id":"90e0dcd","idpDefinitions":{},"prompts":{"username":["text","Email"],"password":["password","Password"]},"timestamp":"2018-03-13T1

### How are you deploying the UAA?

- locally only using gradlew

### What did you do?

1. Create a large amount of saved user cookies in the browser artifically
1. attempt the mfa registration flow with a user.

### What did you expect to see? What goal are you trying to achieve with the UAA?

Expect to see the enter code page.

### What did you see instead?

On pressing next to go from the qr code page to the enter code page, server will return 400.

UAA gets this log:
```
26-Mar-2018 14:21:07.685 INFO [http-nio-8080-exec-7] org.apache.coyote.http11.Http11Processor.service Error parsing HTTP request header
 Note: further occurrences of HTTP header parsing errors will be logged at DEBUG level.
 java.lang.IllegalArgumentException: Request header is too large
	at org.apache.coyote.http11.Http11InputBuffer.fill(Http11InputBuffer.java:706)
	at org.apache.coyote.http11.Http11InputBuffer.parseHeader(Http11InputBuffer.java:853)
	at org.apache.coyote.http11.Http11InputBuffer.parseHeaders(Http11InputBuffer.java:565)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:703)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by 6palace** [comment]
Cool to hear that GDPR is affecting UAA. #775 does help mitigate the problem by reducing cookie expiration to 1 day. It's questionable how useful a saved account is if it's only saved for 1 day though. Ty for response.

**Comment by tnwang** [comment]
Saved Account cookie will still be valid for a year, but will have less attributes and will not be created if account chooser is disabled (discovery can still be enabled even if account chooser is not).

Current Account cookie has only the GUID, and we plan to only keep that around for 1 day, since it's tied to session management with UAA singular, and should not be long lived.

**Comment by shamus** [comment]
Closing due to inactivity.
