### ISSUE TITLE
UAA issue while ssh into the container 

### ISSUE THREAD

**Issue by nsharmacovs** [cloudfoundry/uaa#796]
Hi,

I configured ssh-proxy with diego as per documentation https://docs.cloudfoundry.org/running/config-ssh.html

 i have created client ID ssh-proxy with 
    uaa:
      clients:
        ssh-proxy:
          authorized-grant-types: authorization_code
          autoapprove: true
          override: true
          redirect-uri: /login
          scope: openid,cloud_controller.read,cloud_controller.write,cloud_controller.admin
          secret: SSH-PROXY-SECRET

When i double checked the client details in UAA also .
When i try to execute cf ssh <app> -i 0, i am getting below error from UAA 

5bb
{"access_token":"[PRIVATE DATA HIDDEN]","token_type":"[PRIVATE DATA HIDDEN]","refresh_token":"[PRIVATE DATA HIDDEN]","expires_in":899,"scope":"cloud_controller.read password.write cloud_controller.write openid scim.write scim.read cloud_controller.admin","jti":"313f6a5b9cc14870b119e662ea27bbda"}
0

RESPONSE: [2018-03-29T14:30:41-04:00]
HTTP/1.1 403 Forbidden
Connection: close
Transfer-Encoding: chunked
Cache-Control: no-store
Content-Type: application/json;charset=UTF-8
Date: Thu, 29 Mar 2018 18:30:41 GMT
Pragma: no-cache
Server: Apache-Coyote/1.1
Strict-Transport-Security: max-age=31536000 ; includeSubDomains
Www-Authenticate: Bearer error="insufficient_scope", error_description="Insufficient scope for this resource", scope="uaa.admin uaa.user"
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-Xss-Protection: 1; mode=block

76
{"error":"insufficient_scope","error_description":"Insufficient scope for this resource","scope":"uaa.admin uaa.user"}

below is the curl v2/info 

{
   "name": "Covisint Cloud Foundry - US2",
   "build": "",
   "support": "𝙿𝚂𝚃 ⓐ  covisint.com",
   "version": 0,
   "description": "Cloud Foundry sponsored by Covisint",
   "authorization_endpoint": "https://uaa.sys.us2.XXX.io",
   "token_endpoint": "https://uaa.sys.us2. XXX.io",
   "min_cli_version": null,
   "min_recommended_cli_version": null,
   "api_version": "2.78.0",
   "app_ssh_endpoint": "ssh.run.us2.XXX:2222",
   "app_ssh_host_key_fingerprint": "x:x:x:x:x:x:x:x:x",
   "app_ssh_oauth_client": "ssh-proxy",
   "logging_endpoint": "wss://loggregator.run.us2.XXX:4443",
   "doppler_logging_endpoint": "wss://doppler.run.us2.XXX:4443",
   "user": "ecf80369-17dc-431e-91f6-aac4572918c1"
}

In the UAA Logs i see 

[2018-03-29 18:30:41.708] uaa - 12162 [http-nio-8080-exec-3] .... DEBUG --- FilterSecurityInterceptor: Secure object: FilterInvocation: URL: /oauth/authorize?client_id=ssh-proxy&grant_type=authorization_code&response_type=code; Attribut
es: [#oauth2.throwOnError(#oauth2.hasScope('uaa.user'))]
[2018-03-29 18:30:41.709] uaa - 12162 [http-nio-8080-exec-3] .... DEBUG --- FilterSecurityInterceptor: Previously Authenticated: org.cloudfoundry.identity.uaa.oauth.UaaOauth2Authentication@867cff64: Principal: org.cloudfoundry.identity.
uaa.authentication.UaaPrincipal@e6bdb3ab; Credentials: [PROTECTED]; Authenticated: true; Details: remoteAddress=209.124.43.21, tokenType=bearertokenValue=<TOKEN>; Granted Authorities: uaa.user
[2018-03-29 18:30:41.709] uaa - 12162 [http-nio-8080-exec-3] .... DEBUG --- ExceptionTranslationFilter: Access is denied (user is not anonymous); delegating to AccessDeniedHandler
org.springframework.security.access.AccessDeniedException: Insufficient scope for this resource
        at org.springframework.security.oauth2.provider.expression.OAuth2SecurityExpressionMethods.throwOnError(OAuth2SecurityExpressionMethods.java:72)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:528)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1099)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:670)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1520)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1476)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
Caused by: error="insufficient_scope", error_description="Insufficient scope for this resource", scope="uaa.admin uaa.user"
        at org.springframework.security.oauth2.provider.expression.OAuth2SecurityExpressionMethods.throwOnError(OAuth2SecurityExpressionMethods.java:71)
        ... 80 more
[2018-03-29 18:30:41.714] uaa - 12162 [http-nio-8080-exec-3] .... DEBUG --- DefaultOAuth2ExceptionRenderer: Written [error="insufficient_scope", error_description="Insufficient scope for this resource", scope="uaa.admin uaa.user"] as "application/json;charset=UTF-8" using [org.springframework.http.converter.json.MappingJackson2HttpMessageConverter@3978bdae]

What am i doing wrong here .The UAA release version is v17

**Comment by jspawar** [comment]
@nsharmacovs Can you please update the issue with more details about what your setup is and the steps you're following to see the problem? A lot of the text above is from the issue template that's supposed to guide you toward providing the information we need.

**Comment by nsharmacovs** [comment]
```[2018-03-29 19:22:18.480] uaa - 12898 [http-nio-8080-exec-6] .... DEBUG --- OAuth2AuthenticationProcessingFilter: Authentication success: org.cloudfoundry.identity.uaa.oau
th.UaaOauth2Authentication@e07766e9: Principal: org.cloudfoundry.identity.uaa.authentication.UaaPrincipal@e6bdb3ab; Credentials: [PROTECTED]; Authenticated: true; Details:
 remoteAddress=209.124.43.21, tokenType=bearertokenValue=<TOKEN>; Granted Authorities: uaa.user
[2018-03-29 19:22:18.480] uaa - 12898 [http-nio-8080-exec-6] .... DEBUG --- FilterChainProxy: /oauth/authorize?client_id=ssh-proxy&grant_type=authorization_code&response_t
ype=code at position 11 of 17 in additional filter chain; firing Filter: 'IdentityZoneSwitchingFilter'
[2018-03-29 19:22:18.480] uaa - 12898 [http-nio-8080-exec-6] .... DEBUG --- FilterChainProxy: /oauth/authorize?client_id=ssh-proxy&grant_type=authorization_code&response_t
ype=code at position 12 of 17 in additional filter chain; firing Filter: 'DisableUserManagementSecurityFilter'
[2018-03-29 19:22:18.480] uaa - 12898 [http-nio-8080-exec-6] .... DEBUG --- FilterChainProxy: /oauth/authorize?client_id=ssh-proxy&grant_type=authorization_code&response_t
ype=code at position 13 of 17 in additional filter chain; firing Filter: 'DisableInternalUserManagementFilter'
[2018-03-29 19:22:18.480] uaa - 12898 [http-nio-8080-exec-6] .... DEBUG --- FilterChainProxy: /oauth/authorize?client_id=ssh-proxy&grant_type=authorization_code&response_t
ype=code at position 14 of 17 in additional filter chain; firing Filter: 'SecurityContextHolderAwareRequestFilter'
[2018-03-29 19:22:18.480] uaa - 12898 [http-nio-8080-exec-6] .... DEBUG --- FilterChainProxy: /oauth/authorize?client_id=ssh-proxy&grant_type=authorization_code&response_t
ype=code at position 15 of 17 in additional filter chain; firing Filter: 'ExceptionTranslationFilter'
[2018-03-29 19:22:18.480] uaa - 12898 [http-nio-8080-exec-6] .... DEBUG --- FilterChainProxy: /oauth/authorize?client_id=ssh-proxy&grant_type=authorization_code&response_t
ype=code at position 16 of 17 in additional filter chain; firing Filter: 'FilterSecurityInterceptor'
[2018-03-29 19:22:18.480] uaa - 12898 [http-nio-8080-exec-6] .... DEBUG --- FilterSecurityInterceptor: Secure object: FilterInvocation: URL: /oauth/authorize?client_id=ssh
-proxy&grant_type=authorization_code&response_type=code; Attributes: [#oauth2.throwOnError(#oauth2.hasScope('uaa.user'))]
[2018-03-29 19:22:18.480] uaa - 12898 [http-nio-8080-exec-6] .... DEBUG --- FilterSecurityInterceptor: Previously Authenticated: org.cloudfoundry.identity.uaa.oauth.UaaOau
th2Authentication@e07766e9: Principal: org.cloudfoundry.identity.uaa.authentication.UaaPrincipal@e6bdb3ab; Credentials: [PROTECTED]; Authenticated: true; Details: remoteAd
dress=209.124.43.21, tokenType=bearertokenValue=<TOKEN>; Granted Authorities: uaa.user
[2018-03-29 19:22:18.486] uaa - 12898 [http-nio-8080-exec-6] .... DEBUG --- ExceptionTranslationFilter: Access is denied (user is not anonymous); delegating to AccessDenie
dHandler
org.springframework.security.access.AccessDeniedException: Insufficient scope for this resource
        at org.springframework.security.oauth2.provider.expression.OAuth2SecurityExpressionMethods.throwOnError(OAuth2SecurityExpressionMethods.java:72)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.expression.spel.support.ReflectiveMethodExecutor.execute(ReflectiveMethodExecutor.java:113)
        at org.springframework.expression.spel.ast.MethodReference.getValueInternal(MethodReference.java:129)
        at org.springframework.expression.spel.ast.MethodReference.access$000(MethodReference.java:49)
        at org.springframework.expression.spel.ast.MethodReference$MethodValueRef.getValue(MethodReference.java:347)
        at org.springframework.expression.spel.ast.CompoundExpression.getValueInternal(CompoundExpression.java:88)
        at org.springframework.expression.spel.ast.SpelNodeImpl.getTypedValue(SpelNodeImpl.java:131)
        at org.springframework.expression.spel.standard.SpelExpression.getValue(SpelExpression.java:299)
        at org.springframework.security.access.expression.ExpressionUtils.evaluateAsBoolean(ExpressionUtils.java:26)
        at org.springframework.security.web.access.expression.WebExpressionVoter.vote(WebExpressionVoter.java:52)
        at org.springframework.security.web.access.expression.WebExpressionVoter.vote(WebExpressionVoter.java:33)
        at org.springframework.security.access.vote.AffirmativeBased.decide(AffirmativeBased.java:63)
        at org.springframework.security.access.intercept.AbstractSecurityInterceptor.beforeInvocation(AbstractSecurityInterceptor.java:233)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:124)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:115)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:169)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.cloudfoundry.identity.uaa.scim.DisableInternalUserManagementFilter.doFilterInternal(DisableInternalUserManagementFilter.java:56)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.cloudfoundry.identity.uaa.scim.DisableUserManagementSecurityFilter.doFilterInternal(DisableUserManagementSecurityFilter.java:86)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.cloudfoundry.identity.uaa.zone.IdentityZoneSwitchingFilter.doFilterInternal(IdentityZoneSwitchingFilter.java:134)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.oauth2.provider.authentication.OAuth2AuthenticationProcessingFilter.doFilter(OAuth2AuthenticationProcessingFilter.java:176)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:66)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.cloudfoundry.identity.uaa.web.BackwardsCompatibleScopeParsingFilter.doFilter(BackwardsCompatibleScopeParsingFilter.java:40)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.cloudfoundry.identity.uaa.security.web.SecurityFilterChainPostProcessor$UaaLoggingFilter.doFilter(SecurityFilterChainPostProcessor.java:253)
        at org.cloudfoundry.identity.uaa.security.web.SecurityFilterChainPostProcessor$HttpsEnforcementFilter.doFilter(SecurityFilterChainPostProcessor.java:196)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.cloudfoundry.identity.uaa.oauth.DisableIdTokenResponseTypeFilter.doFilterInternal(DisableIdTokenResponseTypeFilter.java:87)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.cloudfoundry.identity.uaa.zone.IdentityZoneResolvingFilter.doFilterInternal(IdentityZoneResolvingFilter.java:67)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.cloudfoundry.identity.uaa.security.web.CorsFilter.doFilterInternal(CorsFilter.java:222)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.cloudfoundry.identity.uaa.authentication.UTF8ConversionFilter.doFilter(UTF8ConversionFilter.java:56)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
        at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:676)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:528)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1099)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:670)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1520)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
        at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:676)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:528)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1099)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:670)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1520)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1476)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
Caused by: error="insufficient_scope", error_description="Insufficient scope for this resource", scope="uaa.admin uaa.user"
        at org.springframework.security.oauth2.provider.expression.OAuth2SecurityExpressionMethods.throwOnError(OAuth2SecurityExpressionMethods.java:71)
        ... 80 more
[2018-03-29 19:22:18.502] uaa - 12898 [http-nio-8080-exec-6] .... DEBUG --- DefaultOAuth2ExceptionRenderer: Written [error="insufficient_scope", error_description="Insufficient scope for this resource", scope="uaa.admin uaa.user"] as "application/json;charset=UTF-8" using [org.springframework.http.converter.json.MappingJackson2HttpMessageConverter@3d301c73]```

**Comment by DennisDenuto** [comment]
Hi @nsharmacovs 
I *think*  `cf ssh` is using an `oauth token (from the cf cli)` and is trying to get an `authorization code` for the `ssh-proxy` client. This is where it looks like you are getting a `http 403` perhaps because the `oauth token` used is missing the `uaa.user` scope.

Can you please share your `cf` client details?
It should look something like this:
```
 cf:
            access-token-validity: 600
            authorities: uaa.none
            authorized-grant-types: password,refresh_token
            override: true
            refresh-token-validity: 2592000
            scope: network.admin,network.write,cloud_controller.read,cloud_controller.write,openid,password.write,cloud_controller.admin,scim.read,scim.write,doppler.firehose,uaa.user,routing.router_groups.read,routing.router_groups.write,cloud_controller.admin_read_only,cloud_controller.global_auditor
            secret: ''
```

Also I am curious whether the following command works for you:
`cf ssh-code` (This is the authorization code that `cf ssh` gives to the `ssh-proxy` so that it can exchange it for an `authorization token`)

**Comment by nsharmacovs** [comment]
Below is what i have 
 ```  cf:
      access-token-validity: 900
      authorities: uaa.none
      authorized-grant-types: implicit,password,refresh_token
      id: cf
      override: true
      refresh-token-validity: 2592000
      scope: cloud_controller.read,cloud_controller.write,openid,password.write,cloud_controller.admin,scim.read,scim.write,doppler.firehose```

```cf ssh-code
FAILED
Error getting SSH code: Authorization server did not redirect with one time code```

**Comment by DennisDenuto** [comment]
Thanks for the reply @nsharmacovs 

Can you please try adding `uaa.user` scope to your `cf` client.
i.e.
```     
scope: cloud_controller.read,cloud_controller.write,openid,password.write,cloud_controller.admin,scim.read,scim.write,doppler.firehose
```

to this instead:

```
     scope: cloud_controller.read,cloud_controller.write,openid,password.write,cloud_controller.admin,scim.read,scim.write,doppler.firehose,uaa.user
```

**Comment by DennisDenuto** [comment]
Ping @nsharmacovs

**Comment by nsharmacovs** [comment]
uaa.user help me to over come this issue. You can close the case .
