### ISSUE TITLE
Attempting to deploy in JBoss EAP 7.1 results in failure

### ISSUE THREAD

**Issue by mrrumcajz** [cloudfoundry/uaa#871]
**SECURITY NOTICE: If you have found a security problem in the UAA, please do not file a public github issue. Instead, please send an email to security@cloudfoundry.org**

Thanks for taking the time to file an issue. You'll minimize back and forth and help us help you more effectively by answering all of the following questions as specifically and completely as you can.

### What version of UAA are you running?
4.19
What output do you see from `curl <YOUR_UAA>/info -H'Accept: application/json'`
n/a

### How are you deploying the UAA?
JBoss EAP 7.1

I am deploying the UAA in JBoss EAP7.1

### What did you do?

Straight forward deployment of UAA to JBOSS EAP7.1.

### What did you expect to see? What goal are you trying to achieve with the UAA?
Expected application to start with no exceptions

### What did you see instead?
Following is the exception that causes the failure to launch UAA.

2018-07-18 10:30:37,651 ERROR [org.springframework.web.servlet.DispatcherServlet] (ServerService Thread Pool -- 74) Context initialization failed: java.lang.IllegalStateException: UT010041: The servlet context has already been initialized, you can only call this method from a ServletContainerInitializer or a ServletContextListener
	at io.undertow.servlet.spec.ServletContextImpl.ensureNotInitialized(ServletContextImpl.java:870)
	at io.undertow.servlet.spec.ServletContextImpl.addListener(ServletContextImpl.java:687)
	at org.cloudfoundry.identity.uaa.impl.config.YamlServletProfileInitializer.initialize(YamlServletProfileInitializer.java:83)
	at org.cloudfoundry.identity.uaa.impl.config.YamlServletProfileInitializer.initialize(YamlServletProfileInitializer.java:60)
	at org.springframework.web.servlet.FrameworkServlet.applyInitializers(FrameworkServlet.java:730)
	at org.springframework.web.servlet.FrameworkServlet.configureAndRefreshWebApplicationContext(FrameworkServlet.java:667)
	at org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:634)
	at org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:682)
	at org.springframework.web.servlet.FrameworkServlet.initWebApplicationContext(FrameworkServlet.java:553)
	at org.springframework.web.servlet.FrameworkServlet.initServletBean(FrameworkServlet.java:494)
	at org.springframework.web.servlet.HttpServletBean.init(HttpServletBean.java:171)
	at javax.servlet.GenericServlet.init(GenericServlet.java:244)
	at org.cloudfoundry.identity.uaa.web.RecognizeFailureDispatcherServlet.init(RecognizeFailureDispatcherServlet.java:56)
	at io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:117)
	at org.wildfly.extension.undertow.security.RunAsLifecycleInterceptor.init(RunAsLifecycleInterceptor.java:78)
	at io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:103)
	at io.undertow.servlet.core.ManagedServlet$DefaultInstanceStrategy.start(ManagedServlet.java:300)
	at io.undertow.servlet.core.ManagedServlet.createServlet(ManagedServlet.java:140)
	at io.undertow.servlet.core.DeploymentManagerImpl$2.call(DeploymentManagerImpl.java:565)
	at io.undertow.servlet.core.DeploymentManagerImpl$2.call(DeploymentManagerImpl.java:536)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508)
	at io.undertow.servlet.core.DeploymentManagerImpl.start(DeploymentManagerImpl.java:578)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService.startContext(UndertowDeploymentService.java:100)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:81)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
	at org.jboss.threads.JBossThread.run(JBossThread.java:320)

Please include UAA logs if available.

**Comment by DennisDenuto** [comment]
@mrrumcajz Thanks for creating this issue. I *think* what is going on here is that `jboss EAP7.1` is unable to add a listener to the servlet's context (in this case the spring dispatcher servlet) because the servlet implementation that jboss is using [prevents a listener to be added if the servlet context has been initialized](https://github.com/undertow-io/undertow/blob/master/servlet/src/main/java/io/undertow/servlet/spec/ServletContextImpl.java#L715) 

This is not an issue with tomcat (the web application that the uaa team officially supports) because tomcats servlet specification does not contain this validation rule in its servlet implementation.

The `uaa` is currently creating the dispatcher servlet via [web.xml](https://github.com/cloudfoundry/uaa/blob/662244437bfa4cbf257c364b0a3953ce4925e82b/uaa/src/main/webapp/WEB-INF/web.xml#L55-L55) which looks to [create and initialize straight away](https://github.com/cloudfoundry/uaa/blob/e00b0b4a360a0900390f343fd73b7909771eccd1/server/src/main/java/org/cloudfoundry/identity/uaa/web/RecognizeFailureDispatcherServlet.java#L42-L42). Thus by the time the `YamlServletProfileInitializer` [tries to initialize/configure the servlet](https://github.com/cloudfoundry/uaa/blob/e00b0b4a360a0900390f343fd73b7909771eccd1/server/src/main/java/org/cloudfoundry/identity/uaa/web/RecognizeFailureDispatcherServlet.java#L56-L56), jboss throws an exception.

The above is typically used in Servlet 2.5 or earlier environments. However there is another approach available for Servlet 3.0 compatible app servers, which is to configure the Dispatcher Servlet app context via [WebApplicationInitializer](https://docs.spring.io/autorepo/docs/spring/3.2.10.RELEASE/javadoc-api/org/springframework/web/WebApplicationInitializer.html).

That is not a trivial change. This is also not on the uaa team roadmap. I will leave this issue open for discoverability.

**Comment by shamus** [comment]
Closing due to inactivity.
