### ISSUE TITLE
UAA fails irrecoverably after BOSH deploy when manifest has `ldap` in `uaa.delete.identityProviders`

### ISSUE THREAD

**Issue by kindrowboat** [cloudfoundry/uaa#895]
Hello UAA team.  Thank you for all you do.

This bug bit us a few weeks ago.  The tl;dr is that UAA should not allow BOSH to go ahead with a UAA deploy if `uaa.delete.identityProviders` contains `ldap`. Otherwise UAA gets into a wedge state where it responds to authentication API requests with 500s with the following in the logs:

```
Uncaught Exception:
java.lang.IllegalArgumentException: LDAP provider not configured ID:665340d1-0f8d-4e02-8638-1f2d03822f8e
        at org.cloudfoundry.identity.uaa.authentication.manager.DynamicZoneAwareAuthenticationManager.getLdapAuthenticationManager(DynamicZoneAwareAuthenticationManager.java:144)
```

### What version of  are you running?

60.2

### How are you deploying the UAA?

I am deploying the UAA:

using a  release I downloaded from bosh.io

### What did you do?

Our team's application programmatically sets up a BOSH director and its UAA.  We previously supported SAML and internal authentication.  Recently we added LDAP.  We only support one identity provider being enabled at a time.  To ensure that only the activated identity provider is in UAA, and to keep our business logic simple, we put all of the unused identity providers in the `delete.identityProvders` whether or not they were previously installed.

For example, if we were using internal authentication only, we would specify:

```
uaa:
  ...
  delete:
    identityProviders:
    - ldap
    - external-saml-provider
  ...
```

### What did you expect to see? What goal are you trying to achieve with the UAA?

We expect to see the deploy to complete, and to not be able to authenticate with LDAP or the SAML provider.

### What did you see instead?

When we only did this for SAML, this worked as intended.  However, when we started doing this with LDAP, this would put our UAA in an irrecoverable state.  Where the UAA server either does not start or return 500 for all requests.

After talking with the UAA team, we learned that it is unsafe to put `ldap` in the `delete.identityProviders` section.  Instead you are supposed set `uaa.ldap.enabled` to `false`. Doing this fixed the problem. The reason we are reporting this as a bug, is that we think this should be validated before the deployment occurs with a message along the lines of "delete.identityProviders cannot contain ldap". Otherwise, there's no indication or clue why UAA is failing.

#### Logs:
```
[2018-08-14 15:06:04.737] uaa - 10926 [https-jsse-nio-8443-exec-9] .... DEBUG --- FilterChainProxy: /oauth/token at position 1 of 23 in additional filter chain; firing Filter: 'Ua
aMetricsFilter'
[2018-08-14 15:06:04.737] uaa - 10926 [https-jsse-nio-8443-exec-9] .... DEBUG --- UaaMetricsFilter: Successfully matched URI: /oauth/token to a group: /oauth-oidc
[2018-08-14 15:06:04.737] uaa - 10926 [https-jsse-nio-8443-exec-9] .... DEBUG --- FilterChainProxy: /oauth/token at position 2 of 23 in additional filter chain; firing Filter: 'He
aderFilter'
[2018-08-14 15:06:04.737] uaa - 10926 [https-jsse-nio-8443-exec-9] .... DEBUG --- FilterChainProxy: /oauth/token at position 3 of 23 in additional filter chain; firing Filter: 'UT
F8ConversionFilter'
[2018-08-14 15:06:04.737] uaa - 10926 [https-jsse-nio-8443-exec-9] .... DEBUG --- FilterChainProxy: /oauth/token at position 4 of 23 in additional filter chain; firing Filter: 'Co
rsFilter'
[2018-08-14 15:06:04.737] uaa - 10926 [https-jsse-nio-8443-exec-9] .... DEBUG --- FilterChainProxy: /oauth/token at position 5 of 23 in additional filter chain; firing Filter: 'Li
mitedModeUaaFilter'
[2018-08-14 15:06:04.737] uaa - 10926 [https-jsse-nio-8443-exec-9] .... DEBUG --- FilterChainProxy: /oauth/token at position 6 of 23 in additional filter chain; firing Filter: 'Id
entityZoneResolvingFilter'
[2018-08-14 15:06:04.737] uaa - 10926 [https-jsse-nio-8443-exec-9] .... DEBUG --- JdbcTemplate: Executing prepared SQL query
[2018-08-14 15:06:04.738] uaa - 10926 [https-jsse-nio-8443-exec-9] .... DEBUG --- JdbcTemplate: Executing prepared SQL statement [select id,version,created,lastmodified,name,subdo
main,description,config from identity_zone where subdomain=?]
[2018-08-14 15:06:04.739] uaa - 10926 [https-jsse-nio-8443-exec-9] .... DEBUG --- FilterChainProxy: /oauth/token at position 7 of 23 in additional filter chain; firing Filter: 'Di
sableIdTokenResponseTypeFilter'
[2018-08-14 15:06:04.739] uaa - 10926 [https-jsse-nio-8443-exec-9] .... DEBUG --- DisableIdTokenResponseTypeFilter: Processing id_token disable filter
[2018-08-14 15:06:04.739] uaa - 10926 [https-jsse-nio-8443-exec-9] .... DEBUG --- DisableIdTokenResponseTypeFilter: pre id_token disable:false pathinfo:null request_uri:/oauth/tok
en response_type:null
[2018-08-14 15:06:04.739] uaa - 10926 [https-jsse-nio-8443-exec-9] .... DEBUG --- DisableIdTokenResponseTypeFilter: post id_token disable:false pathinfo:null request_uri:/oauth/to
ken response_type:null
[2018-08-14 15:06:04.739] uaa - 10926 [https-jsse-nio-8443-exec-9] .... DEBUG --- FilterChainProxy: /oauth/token at position 8 of 23 in additional filter chain; firing Filter: 'Ht
tpsEnforcementFilter'
[2018-08-14 15:06:04.739] uaa - 10926 [https-jsse-nio-8443-exec-9] .... DEBUG --- SecurityFilterChainPostProcessor$HttpsEnforcementFilter: Filter chain 'tokenEndpointSecurity' pro
cessing request POST /oauth/token
[2018-08-14 15:06:04.739] uaa - 10926 [https-jsse-nio-8443-exec-9] .... DEBUG --- FilterChainProxy: /oauth/token at position 9 of 23 in additional filter chain; firing Filter: 'Ba
ckwardsCompatibleScopeParsingFilter'
[2018-08-14 15:06:04.739] uaa - 10926 [https-jsse-nio-8443-exec-9] .... DEBUG --- FilterChainProxy: /oauth/token at position 10 of 23 in additional filter chain; firing Filter: 'S
ecurityContextPersistenceFilter'
[2018-08-14 15:06:04.739] uaa - 10926 [https-jsse-nio-8443-exec-9] .... DEBUG --- FilterChainProxy: /oauth/token at position 11 of 23 in additional filter chain; firing Filter: 'W
ebAsyncManagerIntegrationFilter'
[2018-08-14 15:06:04.739] uaa - 10926 [https-jsse-nio-8443-exec-9] .... DEBUG --- FilterChainProxy: /oauth/token at position 12 of 23 in additional filter chain; firing Filter: 'H
eaderWriterFilter'
[2018-08-14 15:06:04.739] uaa - 10926 [https-jsse-nio-8443-exec-9] .... DEBUG --- FilterChainProxy: /oauth/token at position 13 of 23 in additional filter chain; firing Filter: 'C
lientParametersAuthenticationFilter'
[2018-08-14 15:06:04.739] uaa - 10926 [https-jsse-nio-8443-exec-9] .... DEBUG --- FilterChainProxy: /oauth/token at position 14 of 23 in additional filter chain; firing Filter: 'C
lientBasicAuthenticationFilter'
[2018-08-14 15:06:04.739] uaa - 10926 [https-jsse-nio-8443-exec-9] .... DEBUG --- JdbcTemplate: Executing prepared SQL query
[2018-08-14 15:06:04.739] uaa - 10926 [https-jsse-nio-8443-exec-9] .... DEBUG --- JdbcTemplate: Executing prepared SQL statement [select client_id, client_secret, resource_ids, sc
ope, authorized_grant_types, web_server_redirect_uri, authorities, access_token_validity, refresh_token_validity, additional_information, autoapprove, lastmodified, required_user_
groups from oauth_client_details where client_id = ? and identity_zone_id = ?]
[2018-08-14 15:06:04.740] uaa - 10926 [https-jsse-nio-8443-exec-9] .... DEBUG --- ClientBasicAuthenticationFilter: Basic Authentication Authorization header found for user 'login'
[2018-08-14 15:06:04.740] uaa - 10926 [https-jsse-nio-8443-exec-9] .... DEBUG --- ProviderManager: Authentication attempt using org.cloudfoundry.identity.uaa.authentication.Client
DetailsAuthenticationProvider
[2018-08-14 15:06:04.740] uaa - 10926 [https-jsse-nio-8443-exec-9] .... DEBUG --- JdbcTemplate: Executing prepared SQL query
[2018-08-14 15:06:04.740] uaa - 10926 [https-jsse-nio-8443-exec-9] .... DEBUG --- JdbcTemplate: Executing prepared SQL statement [select client_id, client_secret, resource_ids, scope, authorized_grant_types, web_server_redirect_uri, authorities, access_token_validity, refresh_token_validity, additional_information, autoapprove, lastmodified, required_user_groups from oauth_client_details where client_id = ? and identity_zone_id = ?]
[2018-08-14 15:06:04.741] uaa - 10926 [https-jsse-nio-8443-exec-9] ....  INFO --- Audit: ClientAuthenticationSuccess ('Client authentication success'): principal=login, origin=[remoteAddress=10.0.0.2, clientId=login], identityZoneId=[uaa]
[2018-08-14 15:06:04.742] uaa - 10926 [https-jsse-nio-8443-exec-9] .... DEBUG --- ClientBasicAuthenticationFilter: Authentication success: org.springframework.security.authentication.UsernamePasswordAuthenticationToken@1122355d: Principal: org.springframework.security.core.userdetails.User@625ef69: Username: login; Password: [PROTECTED]; Enabled: true; AccountNonExpired: true; credentialsNonExpired: true; AccountNonLocked: true; Granted Authorities: uaa.none; Credentials: [PROTECTED]; Authenticated: true; Details: remoteAddress=10.0.0.2, clientId=login; Granted Authorities: uaa.none
[2018-08-14 15:06:04.742] uaa - 10926 [https-jsse-nio-8443-exec-9] .... DEBUG --- FilterChainProxy: /oauth/token at position 15 of 23 in additional filter chain; firing Filter: 'BackwardsCompatibleTokenEndpointAuthenticationFilter'
[2018-08-14 15:06:04.742] uaa - 10926 [https-jsse-nio-8443-exec-9] .... DEBUG --- BackwardsCompatibleTokenEndpointAuthenticationFilter: Processing token user authentication for grant:password
[2018-08-14 15:06:04.742] uaa - 10926 [https-jsse-nio-8443-exec-9] .... DEBUG --- BackwardsCompatibleTokenEndpointAuthenticationFilter: Authentication credentials found password grant for 'admin'
[2018-08-14 15:06:04.742] uaa - 10926 [https-jsse-nio-8443-exec-9] .... DEBUG --- JdbcTemplate: Executing prepared SQL query
[2018-08-14 15:06:04.742] uaa - 10926 [https-jsse-nio-8443-exec-9] .... DEBUG --- JdbcTemplate: Executing prepared SQL statement [select id,version,created,lastmodified,name,origin_key,type,config,identity_zone_id,active from identity_provider where origin_key=? and identity_zone_id=? ]
[2018-08-14 15:06:04.743] uaa - 10926 [https-jsse-nio-8443-exec-9] .... DEBUG --- JdbcTemplate: Executing prepared SQL query
[2018-08-14 15:06:04.743] uaa - 10926 [https-jsse-nio-8443-exec-9] .... DEBUG --- JdbcTemplate: Executing prepared SQL statement [select id,version,created,lastmodified,name,origin_key,type,config,identity_zone_id,active from identity_provider where origin_key=? and identity_zone_id=? ]
[2018-08-14 15:06:04.744] uaa - 10926 [https-jsse-nio-8443-exec-9] .... DEBUG --- SecurityContextPersistenceFilter: SecurityContextHolder now cleared, as request processing completed
[2018-08-14 15:06:04.744] uaa - 10926 [https-jsse-nio-8443-exec-9] .... ERROR --- SecurityFilterChainPostProcessor$HttpsEnforcementFilter: Uncaught Exception:
java.lang.IllegalArgumentException: LDAP provider not configured ID:665340d1-0f8d-4e02-8638-1f2d03822f8e
        at org.cloudfoundry.identity.uaa.authentication.manager.DynamicZoneAwareAuthenticationManager.getLdapAuthenticationManager(DynamicZoneAwareAuthenticationManager.java:144)
        at org.cloudfoundry.identity.uaa.authentication.manager.DynamicZoneAwareAuthenticationManager.getChainedAuthenticationManager(DynamicZoneAwareAuthenticationManager.java:102)
        at org.cloudfoundry.identity.uaa.authentication.manager.DynamicZoneAwareAuthenticationManager.authenticate(DynamicZoneAwareAuthenticationManager.java:71)
        at org.cloudfoundry.identity.uaa.authentication.manager.PasswordGrantAuthenticationManager.authenticate(PasswordGrantAuthenticationManager.java:55)
        at org.cloudfoundry.identity.uaa.authentication.BackwardsCompatibleTokenEndpointAuthenticationFilter.attemptTokenAuthentication(BackwardsCompatibleTokenEndpointAuthenticationFilter.java:202)
        at org.cloudfoundry.identity.uaa.authentication.BackwardsCompatibleTokenEndpointAuthenticationFilter.doFilter(BackwardsCompatibleTokenEndpointAuthenticationFilter.java:112)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:215)
        at org.cloudfoundry.identity.uaa.authentication.ClientBasicAuthenticationFilter.doFilterInternal(ClientBasicAuthenticationFilter.java:74)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.cloudfoundry.identity.uaa.authentication.AbstractClientParametersAuthenticationFilter.doFilter(AbstractClientParametersAuthenticationFilter.java:93)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:66)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.cloudfoundry.identity.uaa.web.BackwardsCompatibleScopeParsingFilter.doFilter(BackwardsCompatibleScopeParsingFilter.java:40)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.cloudfoundry.identity.uaa.security.web.SecurityFilterChainPostProcessor$UaaLoggingFilter.doFilter(SecurityFilterChainPostProcessor.java:255)
        at org.cloudfoundry.identity.uaa.security.web.SecurityFilterChainPostProcessor$HttpsEnforcementFilter.doFilter(SecurityFilterChainPostProcessor.java:198)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.cloudfoundry.identity.uaa.oauth.DisableIdTokenResponseTypeFilter.doFilterInternal(DisableIdTokenResponseTypeFilter.java:87)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.cloudfoundry.identity.uaa.zone.IdentityZoneResolvingFilter.doFilterInternal(IdentityZoneResolvingFilter.java:67)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.cloudfoundry.identity.uaa.web.LimitedModeUaaFilter.doFilterInternal(LimitedModeUaaFilter.java:85)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.cloudfoundry.identity.uaa.security.web.CorsFilter.doFilterInternal(CorsFilter.java:137)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.cloudfoundry.identity.uaa.authentication.UTF8ConversionFilter.validateParamsAndContinue(UTF8ConversionFilter.java:75)
        at org.cloudfoundry.identity.uaa.authentication.UTF8ConversionFilter.doFilter(UTF8ConversionFilter.java:59)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.cloudfoundry.identity.uaa.web.HeaderFilter.doFilter(HeaderFilter.java:52)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.cloudfoundry.identity.uaa.metrics.UaaMetricsFilter.doFilterInternal(UaaMetricsFilter.java:86)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:347)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:263)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
        at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:677)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
[2018-08-14 15:06:04.745] uaa - 10926 [https-jsse-nio-8443-exec-9] .... ERROR --- HomeController: Internal error
java.lang.IllegalArgumentException: LDAP provider not configured ID:665340d1-0f8d-4e02-8638-1f2d03822f8e
        at org.cloudfoundry.identity.uaa.authentication.manager.DynamicZoneAwareAuthenticationManager.getLdapAuthenticationManager(DynamicZoneAwareAuthenticationManager.java:144)
        at org.cloudfoundry.identity.uaa.authentication.manager.DynamicZoneAwareAuthenticationManager.getChainedAuthenticationManager(DynamicZoneAwareAuthenticationManager.java:102)
        at org.cloudfoundry.identity.uaa.authentication.manager.DynamicZoneAwareAuthenticationManager.authenticate(DynamicZoneAwareAuthenticationManager.java:71)
        at org.cloudfoundry.identity.uaa.authentication.manager.PasswordGrantAuthenticationManager.authenticate(PasswordGrantAuthenticationManager.java:55)
        at org.cloudfoundry.identity.uaa.authentication.BackwardsCompatibleTokenEndpointAuthenticationFilter.attemptTokenAuthentication(BackwardsCompatibleTokenEndpointAuthenticationFilter.java:202)
        at org.cloudfoundry.identity.uaa.authentication.BackwardsCompatibleTokenEndpointAuthenticationFilter.doFilter(BackwardsCompatibleTokenEndpointAuthenticationFilter.java:112)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:215)
        at org.cloudfoundry.identity.uaa.authentication.ClientBasicAuthenticationFilter.doFilterInternal(ClientBasicAuthenticationFilter.java:74)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.cloudfoundry.identity.uaa.authentication.AbstractClientParametersAuthenticationFilter.doFilter(AbstractClientParametersAuthenticationFilter.java:93)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:66)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.cloudfoundry.identity.uaa.web.BackwardsCompatibleScopeParsingFilter.doFilter(BackwardsCompatibleScopeParsingFilter.java:40)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.cloudfoundry.identity.uaa.security.web.SecurityFilterChainPostProcessor$UaaLoggingFilter.doFilter(SecurityFilterChainPostProcessor.java:255)
        at org.cloudfoundry.identity.uaa.security.web.SecurityFilterChainPostProcessor$HttpsEnforcementFilter.doFilter(SecurityFilterChainPostProcessor.java:198)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.cloudfoundry.identity.uaa.oauth.DisableIdTokenResponseTypeFilter.doFilterInternal(DisableIdTokenResponseTypeFilter.java:87)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.cloudfoundry.identity.uaa.zone.IdentityZoneResolvingFilter.doFilterInternal(IdentityZoneResolvingFilter.java:67)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.cloudfoundry.identity.uaa.web.LimitedModeUaaFilter.doFilterInternal(LimitedModeUaaFilter.java:85)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.cloudfoundry.identity.uaa.security.web.CorsFilter.doFilterInternal(CorsFilter.java:137)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.cloudfoundry.identity.uaa.authentication.UTF8ConversionFilter.validateParamsAndContinue(UTF8ConversionFilter.java:75)
        at org.cloudfoundry.identity.uaa.authentication.UTF8ConversionFilter.doFilter(UTF8ConversionFilter.java:59)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.cloudfoundry.identity.uaa.web.HeaderFilter.doFilter(HeaderFilter.java:52)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.cloudfoundry.identity.uaa.metrics.UaaMetricsFilter.doFilterInternal(UaaMetricsFilter.java:86)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:347)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:263)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
        at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:677)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by sreetummidi** [comment]
LDAP is a special provider type in UAA and cannot be deleted. Please use the property below to disable is 

https://github.com/cloudfoundry/uaa-release/blob/develop/jobs/uaa/spec#L766-L769
