### ISSUE TITLE
Logging exception due to ipv6 address

### ISSUE THREAD

**Issue by hanswieheiri** [cloudfoundry/uaa#912]
**SECURITY NOTICE: If you have found a security problem in the UAA, please do not file a public github issue. Instead, please send an email to security@cloudfoundry.org**

Thanks for taking the time to file an issue. You'll minimize back and forth and help us help you more effectively by answering all of the following questions as specifically and completely as you can.

### What version of UAA are you running?

What output do you see from `curl <YOUR_UAA>/info -H'Accept: application/json'`
{"app":{"version":"4.14.0"},"links":{"uaa":"http://localhost:8080/uaa","passwd":"/forgot_password","login":"http://localhost:8080/uaa","register":"/create_account"},"zone_name":"uaa","entityID":"cloudfoundry-saml-login","commit_id":"0403be2","idpDefinitions":{},"prompts":{"username":["text","Email"],"password":["password","Password"]},"timestamp":"2018-05-22T17:34:13+0000"}

### How are you deploying the UAA?

I am deploying the UAA
by copying the WAR (renamed to ROOT.war) file that was build with` gradlew clean war -x test` to the tomcat deployment directory. Important to know it runs on Windows Server 2016 and Tomcat 9.0.10 and it used to run with 4.11.0

### What did you do?

From my app redirect to UAA, enter username/pw and redirect back to my app.

### What did you expect to see? What goal are you trying to achieve with the UAA?
Status code 200

### What did you see instead?
Status code 500

Please include UAA logs if available.
```
[2018-10-09 11:17:45.264] cloudfoundry-identity-server - ???? [http-nio-5050-exec-8] .... DEBUG --- AuthzAuthenticationManager: Password successfully matched for userId[Admin]:bfdebc62-e748-42b0-98da-cdae816d2f79
[2018-10-09 11:17:45.264] cloudfoundry-identity-server - ???? [http-nio-5050-exec-8] .... ERROR --- SecurityFilterChainPostProcessor$HttpsEnforcementFilter: Uncaught Exception:
java.util.UnknownFormatConversionException: Conversion = '1'
	at java.util.Formatter.checkText(Unknown Source)
	at java.util.Formatter.parse(Unknown Source)
	at java.util.Formatter.format(Unknown Source)
	at java.util.Formatter.format(Unknown Source)
	at java.lang.String.format(Unknown Source)
	at org.cloudfoundry.identity.uaa.audit.**LoggingAuditService**.log(LoggingAuditService.java:117)
	at org.cloudfoundry.identity.uaa.audit.event.AbstractUaaEvent.process(AbstractUaaEvent.java:68)
	at org.cloudfoundry.identity.uaa.audit.event.AuditListener.onApplicationEvent(AuditListener.java:42)
	at org.cloudfoundry.identity.uaa.audit.event.AuditListener.onApplicationEvent(AuditListener.java:28)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at ...
```
The problem is that Tomcat runs with ipV6 and the IPv6 might have a %-sign in there (maybe just in Windows? :) ) Knowing that one can see the bug on:
https://github.com/cloudfoundry/uaa/blob/0403be2a676e88af2d2ebb171c5ee805c57a8522/server/src/main/java/org/cloudfoundry/identity/uaa/audit/LoggingAuditService.java#L117
`logMessage` already has a `%1` from the ipv6 address and than `String.Format()` cannot deal with it. The possible solution would be to write everything with 1 `String.Format()` statements instead of 2 (or reverse the two statements)

That's the code:
```
@Override
    public void log(AuditEvent auditEvent, String zoneId) {
        updateCounters(auditEvent);
        String logMessage = String.format("%s ('%s'): principal=%s, origin=[%s], identityZoneId=[%s]", auditEvent.getType().name(), auditEvent.getData(),
                auditEvent.getPrincipalId(), auditEvent.getOrigin(), auditEvent.getIdentityZoneId());
        if (auditEvent.getAuthenticationType() != null) {
            logMessage = String.format(logMessage + ", authenticationType=[%s]", auditEvent.getAuthenticationType());
        }
        log(logMessage);
}
```
Thanks for your feedback

**Comment by DennisDenuto** [comment]
Thanks for creating this issue. This has been solved by https://github.com/cloudfoundry/uaa/pull/909/files
