### ISSUE TITLE
Possible memory leak caused by multiple exceptions?

### ISSUE THREAD

**Issue by pivotal-ben-chacko** [cloudfoundry/uaa#973]
UAA 60.11

What output do you see from `curl <YOUR_UAA>/info -H'Accept: application/json'`

UAA deployed as part of PAS 2.3.8 

I am deploying the UAA

- as part of a commercial Cloud Foundry distribution

### What did you do?

During high levels of traffic, the UAA VM ran out of memory and the logs showed the following error message: 

30-Apr-2019 15:45:02.646 SEVERE [http-nio-8080-exec-137] org.apache.catalina.core.ApplicationDispatcher.invoke Servlet.service() for servlet [spring] threw exception
 java.lang.OutOfMemoryError: Java heap space

Also the following stack trace was see many times before the out of memory exception

30-Apr-2019 15:40:10.811 SEVERE [http-nio-8080-exec-10] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [spring] in context with path [] threw exception
 java.lang.IllegalStateException: Cannot call sendError() after the response has been committed
    at org.apache.catalina.connector.ResponseFacade.sendError(ResponseFacade.java:456)
    at javax.servlet.http.HttpServletResponseWrapper.sendError(HttpServletResponseWrapper.java:120)
    at org.cloudfoundry.identity.uaa.security.web.SecurityFilterChainPostProcessor$UaaLoggingFilter.doFilter(SecurityFilterChainPostProcessor.java:273)
    at org.cloudfoundry.identity.uaa.security.web.SecurityFilterChainPostProcessor$HttpsEnforcementFilter.doFilter(SecurityFilterChainPostProcessor.java:198)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
    at org.cloudfoundry.identity.uaa.oauth.DisableIdTokenResponseTypeFilter.doFilterInternal(DisableIdTokenResponseTypeFilter.java:87)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
    at org.cloudfoundry.identity.uaa.zone.IdentityZoneResolvingFilter.doFilterInternal(IdentityZoneResolvingFilter.java:67)

### What did you expect to see? What goal are you trying to achieve with the UAA?
Not sure if there is a correlation between all the exceptions and the VM running out of memory but ideally the code should not be trying to commit the httpresponse object more than once.

Please include UAA logs if available.

**Comment by mwdb** [comment]
HI,

Do you make use of SAML identity providers and have many requests authenticated by SAML?

We run our UAA servers with 1.4 GB/instance and they run stable. We have identified one issue in the past with Java finalizers used by SAML authentication. Under load, the finalizers are not processed fast enough, resulting in out of memory.
We have forked this in our deployment. As Open SAML 2 used by UAA is out of maintenance, we unfortunately can not contribute a fix.
 
Regards,

Martijn

**Comment by shamus** [comment]
Closing due to inactivity.
